### ISSUE TITLE
Gateway ACL?

### ISSUE THREAD

**Issue by dragon2611** [ipfs/ipfs#105]
Apologies if this is the wrong place, but is there any plans to implement an ACL on the HTTP gateway to define which data is allowed to be pulled via that gateway? (I.e has to have originated from your own nodes or some-such)

For instance if running a public HTTP>IPFS gateway to allow embedding on a content on a webpage, one may not want that gateway to allow just anything on the IPFS network as otherwise it is unfortunately likely to be abused.

In an Ideal world it wouldn't be an issue but we don't live in an ideal world and thus some nodes have bandwidth restrictions or are in jurisdictions where law enforcement is likely to be less than understanding about what IPFS actually is.  I.e all they'll see is content was pulled from a HTTP server under your control.

**Comment by jbenet** [comment]
Maybe best to move this to the FAQ: https://github.com/ipfs/faq

I'll answer it here though as i'm currently offline.

> Apologies if this is the wrong place, but is there any plans to implement
an ACL on the HTTP gateway to define which data is allowed to be pulled via
that gateway? (I.e has to have originated from your own nodes or some-such)

You can do this now already with the same ACLs that are on the API server.
Later on we'll have denylists and allowlists for more dynamic control. And
the best case will be the capability/token based auth planned for go-ipfs.
this last one is a few months out though.

> In an Ideal world it wouldn't be an issue but we don't live in an ideal
world and thus some nodes have bandwidth restrictions or are in
jurisdictions where law enforcement is likely to be less than understanding
about what IPFS actually is.

Indeed. see also: https://github.com/ipfs/faq/issues/47

>
