### ISSUE TITLE
Signed up to support savecrypto.org

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipfs#106]
Hey, Quick note to all IPFS watchers here. 

I signed up The IPFS Project to support https://savecrypto.org -- an EFF-led petition asking President Obama to stand up against backdoor keys for encryption. This is one of many actions necessary to ensure encryption is not horribly compromised in the US. 

Since this issue is central to much of what we're doing here, I figured it would be good to also alert everyone watching. Please sign and/or have your orgs endorse. This sort of action is heard. Remember the amazing SOPA/PIPA victory.
### IPFS in good company:

![](http://gateway.ipfs.io/ipfs/QmeWnLPPvFaV6M3MpU88F7FGHTqSrekNBbo48KzVFd5b9W/cap.png)

**Comment by SuperHanZi** [comment]
This is good！
