### ISSUE TITLE
Event Announcements

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipfs#107]
This issue will be to announce events to the watchers of this repo. We may have events that are not announced here. for best results, watch https://github.com/ipfs/community (we will also have a calendar soon).

So far, two new _recurring_ events just popped up:
- **Portland:** IPFS Enthusiasts -- starts 2015-10-14 -- http://calagator.org/events/1250469161 -- discuss here: https://github.com/ipfs/community/issues/49 cc @brixen
- **Copenhagen:** IPFS Meetup -- starts 2015-11-28 -- http://www.meetup.com/Copenhagen-IPFS-Meetup/events/225899409/?a=socialmedia discuss here: https://github.com/ipfs/community/issues/51 cc @NeoTeo

One offs: 
- **Palo Alto or San Francisco:** an IPFS Meetup on 2015-10-20 -- details TBD. discuss here -- https://github.com/ipfs/community/issues/53

If you announce something here, please keep it to a short entry like those above, making sure to list location, time, and links to events and to an issue in https://github.com/ipfs/community/issues/ for further discussion.

**Comment by RichardLitt** [comment]
We now have [a calendar](https://www.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84%40group.calendar.google.com&ctz=America/New_York). Please ping if items added here aren't added to the calendar swiftly.

**Comment by frabrunelle** [comment]
**Montreal:** SAFE + IPFS Meetup on 2015-12-08 -- https://montreal.safenetwork.org/2015/11/25/safe-ipfs-meetup/ -- discuss here: ipfs/community#87

**Comment by jbenet** [comment]
Hey Everyone, we're having a meetup wed night in Cambridge (Boston) at MIT. 

- April 20, 2016 from 6:30 PM to 8:30 PM (EDT)
- Eventbrite: https://www.eventbrite.com/e/ipfs-ethereum-mit-meetup-tickets-24578852008
- Event Discussion: https://github.com/ipfs/community/issues/115 

![](https://ipfs.io/ipfs/QmT7kuXkrpG9TeCdZWfCkE7eqVu5aoje1dDAURmvVSuJ1k/ipfs-meetup-mit.jpg)

**Comment by RichardLitt** [comment]
Hey all! We have a workshop next week, in Lisbon but also accessible remotely. Take a look at this issue announcing it: https://github.com/ipfs/community/issues/142

tl:dr; An IPFS Workshop and hackday, in Lisbon, July 25th-26th, accessible remotely, all invited, proposals for talks and events encouraged, travel scholarships available as needed.
