### ISSUE TITLE
Python//IPFS dev discussion

### ISSUE THREAD

**Issue by amstocker** [ipfs/ipfs#112]
re: https://github.com/ipfs/pm/issues/34

I am interested in starting some more discussion aimed at developing with Python in the IPFS ecosystem.  This would include a hangouts vid-chat and/or irc discussion as part of our monday sprints.  Some possible topics off of the top of my head:
- IPFS Extensions for popular web frameworks e.g. django, flask, etc.
- Eventually; a partial or full implementation of the IPFS protocol in Python (or C? -- that's a scary thought)
- ???

I'm particularly interested in the case of web apps that use IPFS as a backend and can scale simply by adding more nodes/processes.  In general I think this would require a pub/sub or messaging framework for coordination (see discussions: https://github.com/ipfs/notes/issues/64, https://github.com/ipfs/notes/issues/40, https://github.com/ipfs/apps/issues/10), but I think for now there should exist a nice library for small webapps that would allow one to use IPFS as a simple backend database.

Some existing projects:
- [Git on IPFS](https://github.com/larsks/git-remote-ipfs)
- [WebRecorder.io on IPFS](https://github.com/ipfs/apps/issues/3)
- We've also started an [api client for python](https://github.com/ipfs/python-ipfs-api) which is mostly stable but could still use some more work.

I am excited to hear if anyone would be interested in this, and if anyone has any more suggestions/ideas put 'em here.

**Comment by lwm** [comment]
Hey, I was day dreaming of a django app with a distributed backend and found myself here. The api client that is already on the go looks quite cool. Did anything happen related to Django? I'm pretty new to IPFS but would love to give a shot at moving this along.

**Comment by TKorr** [comment]
To implement IPFS in full (not just an API) would require some of the libp2p modules to be implemented first. only a handful have been done [ipfs/py-ipfs](https://github.com/ipfs/py-ipfs).
A Django app would be the dream of course but it looks like we have some work to do first. Add your name to the email thread [py-ipfs/notes#1](https://github.com/ipfs/py-ipfs/issues/1) for people interested in contributing.

**Comment by lwm** [comment]
Thanks @TKorr. I've dropped a comment there and will see what else I can do.

**Comment by diasdavid** [comment]
I wrote this https://github.com/ipfs/community/issues/177 a while ago to help new language implementations get started. Looking forward to see the py-ipfs implementation!

**Comment by diasdavid** [comment]
Let's follow on https://github.com/ipfs/py-ipfs/issues/33
