### ISSUE TITLE
Feature: aggregate storage used/free and bandwidth stats

### ISSUE THREAD

**Issue by donpdonp** [ipfs/ipfs#113]
Is there any metadata being passed around along with IPFS traffic? It would be exceptionally useful to aggregate the total storage used/free amongst all IPFS nodes and chart it somewhere. Average bandwidth as well. Being able to see the network grow by charting this data, and also an indicator of a network-wide attack on IPFS would be features of this data.

**Comment by jbenet** [comment]
thanks @donpdonp  this should go in one of the relevant implementations, probably https://github.com/ipfs/go-ipfs/ -- or specs https://github.com/ipfs/specs if desired for all impls.

**Comment by jbenet** [comment]
(this repo is mostly for news)
