### ISSUE TITLE
Proposal: IPNS like Git's HEAD | Non-Destroyable IPNS Links

### ISSUE THREAD

**Issue by ilyaigpetrov** [ipfs/ipfs#114]
Currently ipns resolves this way:   `ipns_addr >> ipfs_obj`
What about:
`ipns_addr >> HEAD -> ipfs_obj, prev_head -> prev_ipfs_obj, prev_head -> ... -> 1st_ipfs_obj, null`

Why is this better?
Because ipns owner won't be capable of erasing the truth once stated in the network.
E.g. if we keep [sins per each person](https://gist.github.com/ilyaigpetrov/47980368184e03d6d152), even if you hack all ipns owners you won't be able to erase your sins.

@whyrusleeping pointed me to [IPRS](https://github.com/ipfs/specs/tree/master/records) but I hardly get it.

#### Problems

For quickly mutating ipns (years of streaming media) you will have a very long chain of commits to keep somewhere.

**Comment by jbenet** [comment]
version history commits should be IPFS objects, not IPNS records. think about it this way: an ipns name is like a git branch, not like a git commit. the {git branch, ipns name} _points to_ a commit.

there are cases where IPNS ancestry chains make sense, bit not on every case. try reading the IPRS spec again, and the PR that introduced it as it has discussion as to why this doesn't make sense for every case.

also, this should be over in https://github.com/ipfs/faq -- we can have more discussion there

**Comment by jbenet** [comment]
(and yes, your gisted idea would prefer ancestry chains, and you can do that, but it's not a requirement for _all_ ipns records)

**Comment by jbenet** [comment]
(and yes, your gisted idea would prefer ancestry chains, and you can do that, but it's not a requirement for _all_ ipns records)

**Comment by kenCode-de** [comment]
Where has the IPRS records stuff gone? 
Broken: https://github.com/ipfs/specs/tree/master/records

**Comment by Kubuxu** [comment]
https://github.com/ipfs/specs/tree/master/iprs-interplanetary-record-system

**Comment by kenCode-de** [comment]
sweet, thanx Kubuxu :)
