### ISSUE TITLE
Questions - 2014 Filecoin and related IPFS 

### ISSUE THREAD

**Issue by MaxEntropyy** [ipfs/ipfs#115]
Hello...

I have recently read the 2014 Filecoin and I understand from the IPFS website that Filecoin will follow the V1.0 release of IPFS. I am considering the use of IPFS and possibly Filecoin in a telco communications environment for a modified type of messaging; and for high latency network file stores.

Several questions come to mind...

Questions:

Q1: is there an implementation of the Filecoin system?

Q2: if so, then have there been any performance analysis tests run that you can publish for file size boundary cases?

Q3: I am interested in Proof of Retrievability Challenges... Is there a discussion of the different cases to be considered?

Q4: I have looked for an implementation of the Gateway.ipfs.io executable and I don't believe it is at the IPFS Github repository. Did I miss it?

If there is a more appropriate place to ask these questions please direct me to that location.

With kind regards,
jds

**Comment by jbenet** [comment]
thanks jds. Please ask IPFS questions in the https://github.com/ipfs/faq/ -- this repo is mainly for news. Filecoin questions i'll answer in your separate email.
