### ISSUE TITLE
How are IPFS objects stored?

### ISSUE THREAD

**Issue by sic2** [ipfs/ipfs#119]
Thank you for this project first of all. 
I am trying to get my head around a couple of things. I have already read the paper (draft3) and watched some of the videos. 

My first question is: how are IPFS objects stored? and where? 
I have noticed this directory in my machine `.ipfs/datastore` and it seem to contain logfiles, a manifest and a database file. However, none of these files is readable (I see only bytes) and I cannot find any tool to open them. I am assuming that IPFS objects are stored in the database file in some format. Otherwise, how else are they stored? This is a bit confusing because in the paper it looks like there are IPFS files containing JSON-like information about the DAG graph. However, I am not clear where these files are and what formats they have.

My second question is related to locations. IPFS uses DHTs, so when a peer receives a requests it looks for that hash (or multihash) and if found, it checks where it is in the machine (say `/User/Jonny/Documents/image_of_fish.jpg`). If that is how it works internally, where could I find this mapping under the `.ipfs/` directory? If that is not the case, how does the system know where the data is in the machine?

Maybe a bit of more clarification on what is stored under `.ipfs/` and in what format would really help.

Thank you!
Ivan

**Comment by whyrusleeping** [comment]
This might help: https://github.com/ipfs/specs/tree/master/repo

In short, all content in ipfs is chunked into blocks and blocks are stored on disk under $IPFS_PATH/blocks

**Comment by sic2** [comment]
Thanks! I see there is a high level description of what the different files are. I will try and figure out things myself and come back here if necessary.

**Comment by wellorange** [comment]
@whyrusleeping I have a problem，When users add a file, how does bitswap back up this file to the network?

**Comment by whyrusleeping** [comment]
No, data is only on your computer until someone else decides to fetch it

**Comment by wellorange** [comment]
@whyrusleeping I understand, thank you

**Comment by Stebalien** [comment]
(closing as we now use discuss.ipfs.io for questions)
