### ISSUE TITLE
Proofreading Frenchi Wikipedia article

### ISSUE THREAD

**Issue by edouard-lopez** [ipfs/ipfs#122]
Hi guys,
I translated the [English article](https://en.wikipedia.org/wiki/InterPlanetary_File_System) into [the French wikipedia](https://fr.wikipedia.org/wiki/IPFS). As I'm no expert in data storage nor P2P technology, I reckon there is mistranslation, and a **proofreading should be done for accuracy-sake**.

Thanks.

**Comment by cloutier** [comment]
I will take a look at that today.

Je vais vérifier tout ça tantôt. J'étudie l'informatique et la programmation en français et je connais bien le vocabulaire.

**Comment by cloutier** [comment]
J'ai traduit la citation et j'ai fait quelques petits changements, mais c'est une très bonne traduction au final. Je vais continuer d'essayer de le rendre plus facile d'accès pour les néophytes, mais l'article en anglais a le même problème.

@jbenet I'd like to add the ipfs logo to both the French and the English article. Can you release it under a creative common licence?

**Comment by edouard-lopez** [comment]
@cloutier merci pour la relecture !
