### ISSUE TITLE
Merge project directory with awesome-ipfs?

### ISSUE THREAD

**Issue by fazo96** [ipfs/ipfs#127]
The [project directory](https://github.com/ipfs/ipfs/blob/master/project-directory.md) in this repo has many sections, maybe some of them (like Applications) should be merged with [awesome-ipfs](https://github.com/ipfs/awesome-ipfs) for example by linking awesome-ipfs here instead of having duplicate data

**Comment by RichardLitt** [comment]
Good point! We're working on revamping project-directory (mostly by just removing it entirely) and putting it into the main README and ipfs/community/contributing.md. If you want a long slog, see https://github.com/ipfs/ipfs/pull/125. 

Linking aweome-ipfs in the README here makes sense.

**Comment by mekarpeles** [comment]
+1 for linking or including the contents of awesome-ipfs directly within README

Separately proposing (for the same reasons as project-directory.md) consolidation of awesome-ipfs into appropriate repos. We have a lot of repos (with very little content) which requires a lot of context switching and confusion about what goes where.

**Comment by jbenet** [comment]
I think awesome-ipfs should remain a separate list. It is specifically a thing meant to include apps.

I only want to highlight a few here in the main repo. Maybe we could even remove most of the apps from here (except webui, station, and things used for IPFS itself / to build ipfs)

**Comment by dali99** [comment]
You could always move awesome-ipfs to the wiki.

**Comment by mekarpeles** [comment]
@dali99 i hear generally ipfs discourages wiki as it has less stringent and granular code review + version control process.

I personally think the awesome list should just be merged with the correct repos, but the real priority is the main readme is fresh.

**Comment by dali99** [comment]
@mekarpeles I thought wiki's were git repos themselves, like https://github.com/ipfs/ipfs.wiki.git I don't think it's as easy to see changes online on these, but git history should let you see the entire commit log.

**Comment by mekarpeles** [comment]
@dali99 I believe it's more the code review element (being able to branch, more easily collaboratively edit, etc)

**Comment by RichardLitt** [comment]
I agree about not moving to a wiki, for the reasons mentioned above. 

I don't think merging the awesome-list completely is a good idea: as Juan stated, it is a separate thing. CF sindresorhus/awesome for more about that. I'm in charge of a few awesome lists, so I know that ecosystem very well; I'd not feel comfortable with it having an awesome-* tag if it didn't match their standards. 

> I only want to highlight a few here in the main repo. Maybe we could even remove most of the apps from here (except webui, station, and things used for IPFS itself / to build ipfs)

This sounds right to me.

**Comment by fazo96** [comment]
> I only want to highlight a few here in the main repo. Maybe we could even remove most of the apps from here (except webui, station, and things used for IPFS itself / to build ipfs)

I think this is the best approach. Also we need a link to awesome-ipfs in the README here I guess.

**Comment by diasdavid** [comment]
Agree, having to update 2 lists is hard and confusing.

**Comment by RichardLitt** [comment]
Hmm. Maybe I can explain this better: _awesome-ipfs_ should not be comprehensive, by it's definition as an _awesome-*_ list. Awesome-lists should only be for things that are awesome - however, some resources, while cool, may not satisfy, hence why we have project directories elsewhere. 

In the meantime since this issue was opened, we've overhauled the project directory - it is now directly in the README, and there is a link to awesome-ipfs: see [this commit and line](https://github.com/ipfs/ipfs/pull/128/files#diff-04c6e90faac2675aa89e2176d2eec7d8R275) or check out  https://github.com/ipfs/ipfs directly. 

We could display the awesome list more prominently? I think directly under [Project and Community](https://github.com/ipfs/ipfs#project-and-community), to highlight cool stuff the community has made.

**Comment by RichardLitt** [comment]
@fazo96 How does that look?

**Comment by fazo96** [comment]
Very nice! Exactly what I was suggesting :+1: Also I really like the new README structure overall!

**Comment by RichardLitt** [comment]
_Awesome._
