### ISSUE TITLE
Linux syslog integration

### ISSUE THREAD

**Issue by mercurytw** [ipfs/ipfs#133]
As a linux server administrator, I would like to have the option of redirecting stdout, stderr, and logging to the linux syslog (for which there is a go library), so that I can easily view log output at the same aggregation point as the other daemons I manage and monitor.

**Comment by jbenet** [comment]
is this a feature request for https://github.com/ipfs/go-ipfs ?

**Comment by mercurytw** [comment]
ah yeah. sorry.
