### ISSUE TITLE
[Bug] Error: resource temporarily unavailable

### ISSUE THREAD

**Issue by karv** [ipfs/ipfs#135]
Had been trying ipfs, everything was going well,
I was about to connect to my other computer but suddenly the daemon crashed, i wanted to restart it but...

    $ ipfs daemon
    Initializing daemon...
    Error: resource temporarily unavailable

OS: Ubuntu 15.10 64 bits
ipfs version 0.3.10-dev (prebuilt)

**Comment by karv** [comment]
Must add, happened after an `ipfs ls` command.

**Comment by whyrusleeping** [comment]
how did it crash? what happened?

**Comment by jbenet** [comment]
@karv I moved this to the proper support forum: https://github.com/ipfs/support/issues/12
