### ISSUE TITLE
Consider link to ipfs-browser

### ISSUE THREAD

**Issue by crazysoldier** [ipfs/ipfs#136]
i wrote a simple webkit Browser to access websites on ipfs. 
I will make it better over time but it works as expected for now. 

https://github.com/crazysoldier/ipfs-browser

Lg.

**Comment by fazo96** [comment]
Maybe try asking on https://github.com/ipfs/awesome-ipfs

I don't think applications belong here

**Comment by RichardLitt** [comment]
Yep, @fazo96 has it right. Thanks, @crazysoldier, though! Looks cool.

**Comment by Physes** [comment]
Hi @crazysoldier I'm wondering if you'd be interested in joining an IPFS startup? It's an Ethereum-based IPFS DNS system called Nebulis along with an IPFS browser called Nebula. Send me an email at philipsaunders@protonmail.com.

**Comment by RichardLitt** [comment]
@Physes This is not an appropriate place to post that. Thanks.

**Comment by jbenet** [comment]
We should probably create a venue for this. maybe the ipfs-users mailing list, or maybe elsewhere. more people will want to find team mates and/or projects looking for people around the IPFS ecosystem. 

cc @flyingzumwalt thoughts on a good venue for this?

**Comment by Physes** [comment]
My apologies by the way- I just couldn't see another way of contacting @crazysoldier since there is no messaging facility. Some kind of a board would be valuable- my intention wasn't to be disrespectful. Thanks.

**Comment by jbenet** [comment]
Actually let's discuss that here: https://github.com/ipfs/notes/issues/167

**Comment by RichardLitt** [comment]
Good call, @jbenet. Thanks, @Physes.
