### ISSUE TITLE
Separate addressable object from object

### ISSUE THREAD

**Issue by FormalPrivacy** [ipfs/ipfs#139]
There's a consistent issue with most merkle-dag systems that they conflate two things that eventually makes the system difficult to build upon:

1. An object that has a defined hash value.
2. An object that is addressable

By separating these two, it is possible to:

1. In the storage backend, inline small objects.
1. Make standard data types that compose well without causing a false dichotomy between this and a blowup in the number of addressable objects in storage.
1. Restating the above, utilize smaller objects which means increasing the practical expressiveness of the system.  Anyone familiar with functional programming can attest to the fact that small objects compose better.
1. As a use-case, standardize signature construction without imposing unneeded overhead of exposing access to the "naked" data.  Again, the git commit object is an example of a badly designed node where these concerns are conflated, making the data structure for the signature scheme not composable.
1. As a use-case, efficiently support storage of binary trees optimized by access pattern and/or storage system (storage system decides chunk size).
1. As a use-case, efficiently support fine-grained parallel hash modes with no storage overhead (by injecting not-addressable nodes in the structure).
1. Naturally map to tree-hashing modes in modern hash functions.

I propose a minimal solution to this which is simply a reserved bit in the multi-hash namespace header that indicates whether the node is addressable or not.  A not-addressable object can never be used in a top level `ipfs` command.

Whether a storage backend stores this object separately or not is an optimization issue.  When such an object is stored "inline", there is no need to store the hash of the object anywhere, and thus there is no overhead. An object that is smaller than its own hash size is not useful to store separately for example.

Two issues not addressed that I'm not going into here:  1) a query language for getting non-addressable objects inlined into an API response (to improve efficiency), and 2) Referring to a non-addressable node given that the storage system wants to keep the invariant that no node has dangling references (ref language that starts at addressable node is a solution).

**Comment by jbenet** [comment]
Please file this under the notes repo: https://github.com/ipfs/notes/
