### ISSUE TITLE
"ipfs mount" gives "Error: could not resolve name."

### ISSUE THREAD

**Issue by ScoreUnder** [ipfs/ipfs#144]
In the 0.4.0-dev branch, trying to run `ipfs mount -t (path) -n (path)` results in this output on the daemon's side:
```
02:03:36.078 ERROR  fuse/ipns: looking up /ipns/QmWwFzprnzTyuN1YNsVjTgsYRuqHQpLz6r5JkgPiaMz4EJ: could not resolve name. ipns_unix.go:90
02:03:36.088 ERROR core/comma: error mounting: %!s(<nil>) could not resolve name. mount_unix.go:219
```
The directories do not end up mounted.

**Comment by Kubuxu** [comment]
It means that you are offline ipfs/go-ipfs#2167

**Comment by ScoreUnder** [comment]
That's correct. I'll close this then as it's the same issue.
