### ISSUE TITLE
Consider capnproto instead of protobufs

### ISSUE THREAD

**Issue by pjz** [ipfs/ipfs#15]
Protobufs has a successor you might want to use instead:

http://kentonv.github.io/capnproto/

**Comment by t128** [comment]
don't think a *multicodec* is a good idea. At the end you need to support all the codecs. Also i don't really see a advantage of storing the blockinfos in varying codecs.

**Comment by traverseda** [comment]
bump (consider closing this if it's no longer relevant)

**Comment by lgierth** [comment]
We've decided to go with CBOR for IPLD's canonical data encodings: https://github.com/ipld/ipld
