### ISSUE TITLE
TestFilePersistence and TestMultipleDirs fuse tests fail

### ISSUE THREAD

**Issue by thelinuxkid** [ipfs/ipfs#153]
https://travis-ci.org/thelinuxkid/go-ipfs/jobs/102976905#L252
https://travis-ci.org/thelinuxkid/go-ipfs/jobs/102976905#L255

**Comment by jbenet** [comment]
@thelinuxkid did yo mean to file these in https://github.com/ipfs/go-ipfs?

**Comment by thelinuxkid** [comment]
Yes sorry.  Will fix when I get home.

Typed with thumbs
