### ISSUE TITLE
Quick question about data flow

### ISSUE THREAD

**Issue by falsechicken** [ipfs/ipfs#154]
Hello. I am new to IPFS and I am wondering how data flows through the mesh. A friend of mine and I where talking about potential legal problems that arise from this. Specifically the transfer of illegal content.

I am under the assumption that peers only store data they are WILLING to store. Via pinning or visiting a site/resource manually. Meaning that if there is illegal content floating around out there the innocent parties that do not want to touch this data do not have to transfer it. Therefore keeping them innocent.

My question is: Do the nodes on the network that do not have the data simply refer the asking client to a node that actually has the data or do the nodes have to pass the data through them and deliver it to the client that requests it? Thanks!

**Comment by fr34kyn01535** [comment]
I am the friend ;D What is with DCMA or simply illegal content like child porn or terroristic file share (bomb plans or whatever)..

**Comment by jbenet** [comment]
Welcome to the community. Thanks for asking -- please look at the FAQ -- questions like these are well covered. https://github.com/ipfs/faq/issues -- specifically, search for "content model" and for "resolution"
