### ISSUE TITLE
Allow --version

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/ipfs#158]
I type ` ipfs --version` a lot, and it tells me nothing just `Error: Unrecognized option 'version'`. Would be nice to be able to have `--version` also return something, just like `ipfs --help` does.

**Comment by harlantwood** [comment]
Agree, I often forget to leave off the dashes.

**Comment by RichardLitt** [comment]
Tried to make a PR. Not sure I know enough Golang for this one.

**Comment by RichardLitt** [comment]
Closing this. It should be elsewhere.
