### ISSUE TITLE
how IPFS will do smart hosting contracts ?

### ISSUE THREAD

**Issue by icf20** [ipfs/ipfs#162]
hi, i dont know if this is the bet place to ask this, i have no idea where to ask

this is how i understand and see the smart hosting contract. 
- the contract can have a time hosting limit and a bandwidth hosting limit and the contract and the contract is fulfilled if one of the conditions are meet  
- for example minimum 20 days hosting contract and up to 100 GB of bandwidth 
- start-request condition, so if someone host a video the counter goes up only if the website visitor want to see the video not just the host attempting to cheat 

the man question is what IPFS will do to accommodate a type of contract like this ?

**Comment by RichardLitt** [comment]
Hi @icf20! Thanks for this. 

This belongs in [ipfs/faq](//github.com/ipfs/faq). Can you open an issue with this content, there? [Here is a link to do so](//github.com/ipfs/faq/issues/new). Thanks!
