### ISSUE TITLE
cli and web UI produce 2 different hash 

### ISSUE THREAD

**Issue by dontspamm** [ipfs/ipfs#163]
this is based on the discussion on spanish zerotalk (  165eqHdoQfyf7CVGqtVCGNDvMBZhwVSJBL )

the file give this hash if is added using the CLI ipfs add filename  Qmeq7Ew88BdSHZVjgUrrDHEqf3ZucMLkz5VQ6HLBh8QKo1 

if you drag and drop the same file using the webUI it give this hash QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH

**Comment by RichardLitt** [comment]
Thanks @dontspamm!

This belongs in ipfs/support. Can you [open a new issue there?](//github.com/ipfs/support/issues/new)

**Comment by lidel** [comment]
This can be closed in favor of https://github.com/ipfs/support/issues/45 and https://github.com/ipfs-shipyard/ipfs-webui/issues/676
