### ISSUE TITLE
When will data be permanently available?

### ISSUE THREAD

**Issue by brainframe-me** [ipfs/ipfs#165]
I'm considering using IPFS as a permanent ledger for certain data we host. As far as I understood it, the idea is that one does an "ipfs add" of the files, this creates a hash, which will be available from https://ipfs.io/ipfs/hash. I noticed it takes a while before the data is available via this central point, but I would like to know from when on I can consider it to be online permanently?
And can I be sure it will be online permanently?

**Comment by noffle** [comment]
There may be a misunderstanding. IPFS is not a "permanent ledger" for data hosted. At least not in the way that e.g. Bitcoin is a permanent ledger for transactions. There is no blockchain.

IPFS is a distributed system that can (among other things) can resolve a content hash to the content it represents. This content can never truly be *guaranteed* to be available (maybe you're offline, maybe all of the peers with it are offline, maybe you're behind a powerful NAT, maybe the network split and the peers with the content are on the other partition).

IPFS' internals do many things to maximize that availability (NAT traversal, Kademlia routing for finding content, etc), but you can also make various efforts to increase its availability: pinning your data (telling your IPFS node to keep a content hash and its content around indefinitely), paying the operators of other nodes to pin your data as well, or running many nodes yourself.

**Comment by jbenet** [comment]
I just added the following to ipfs/faq#47

> **Q: how can i ensure something remains online?**
> A: you can do this by keeping one or several ipfs nodes online pinning the content you're interested in backing up, the more ipfs nodes pinning content, the better redundancy you get. Tools such as [ipfs-persistence-consortium](https://github.com/pipermerriam/ipfs-persistence-consortium), [pincoop](https://github.com/VictorBjelkholm/pincoop), and [ipfs-cluster](https://github.com/ipfs/notes/issues/58) on top of ipfs allow you to share the costs of bandwidth with other people or organizations. Then, protocols like [Filecoin](http://filecoin.io) will allow you to just pay the network to do it for you (i.e. similar to how people pay "the cloud companies", but here you're paying the network itself). (Filecoin is not live yet)

**Comment by brainframe-me** [comment]
Ok, thanks for this clarification!
