### ISSUE TITLE
'ipfs update' throws strange error on OS X.

### ISSUE THREAD

**Issue by cb0** [ipfs/ipfs#171]
As I'm not quite sure if the `update` command is supported or working yet. It however throws a strange error I would like to report.
Under Mac OS X I get the following error:

```
➜  ipfs update
Error: %!s(MISSING) not installed.
```

This is my current config:

```
➜  ipfs version
ipfs version 0.3.11
➜  sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.11.3
BuildVersion:   15D21
```
It might be nothing ...

**Comment by machawk1** [comment]
Same on 10.11.4
```sh
$ ipfs update
Error: %!s(MISSING) not installed.
$ ipfs version
ipfs version 0.3.11
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.4
BuildVersion:	15E65
```

**Comment by RichardLitt** [comment]
Thanks for pointing this out! This is, I think, a known issue. It should put on ipfs/support, but I'm directing @whyrusleeping here.

**Comment by lgierth** [comment]
I think you might not have `ipfs-update` installed, it's not part of `go-ipfs` -- you can get it at http://dist.ipfs.io

**Comment by whyrusleeping** [comment]
_for the moment_ you will need to install `ipfs-update` yourself. This is somewhat inconvenient, but getting this bootstrapping working right is difficult.

To install `ipfs-update` you have two options. If you have go installed, you can simply run `go get github.com/ipfs/ipfs-update`. If you don't have `go` installed, you can grab a binary of `ipfs-update` from http://dist.ipfs.io and install it into your path.

**Comment by cb0** [comment]
Thanks for the clarification. 
I tried installing through `go get github.com/ipfs/ipfs-update` and it did work. What I forgot was to add my `$GOPATH` bin folder to my `$PATH`. It's not a big problem to install this separately, but I must have missed it in the quick-start readme.
