### ISSUE TITLE
You will have problems with the law...

### ISSUE THREAD

**Issue by monoflash** [ipfs/ipfs#172]
If someone will fill in ipweb child pornography or something is not legitimate then you will have problems with the law.
Do not use ipweb, before it is not possible to delete data!

**Comment by RichardLitt** [comment]
Thanks @monoflash for raising these concerns. We have dealt with these elsewhere: for instance, here https://github.com/ipfs/faq/issues/36#issuecomment-140567411. This is not an insurmountable issue. 

If you have more questions, I would direct them to https://github.com/ipfs/faq. Thanks.

**Comment by jbenet** [comment]
To be crystal clear: by default, ipfs does not download things you did not explicitly ask for.
