### ISSUE TITLE
IPFS on The Changelog!

### ISSUE THREAD

**Issue by jerodsanto** [ipfs/ipfs#173]
Howdy from [The Changelog](https://changelog.com/)!

We'd love to have you on the show sometime soon. Who would be best to have on the show to talk about this project and what you're up to? Feel free to send an email to editors@changelog.com to coordinate.

If you haven't heard of the show, The Changelog is a weekly podcast that covers what's fresh and new in open source. You can listen to the show here http://thechangelog.com/podcast/ or here http://5by5.tv/changelog

Looking forward to talking to y'all!

**Comment by jbenet** [comment]
@jerodsanto oh thanks! We'd love to! Will send email to coordinate. 😄 👍

**Comment by VictorBjelkholm** [comment]
This happened and the episode is available here: https://changelog.com/podcast/204
