### ISSUE TITLE
ipv6 and ipfs - binding to addresses that cannot be reached

### ISSUE THREAD

**Issue by dtaht** [ipfs/ipfs#178]
I have no idea why ipfs would swarm to localhost (somewhere else) nor ULAs such as fdda:whatever - or basically any address I cannot ping/reach.... I also saw it show some addresses in a range I'd never seen before (2003::). 

I was pleased to see some support for utp emerge. the bufferbloat on the tcp stuff has to be seen to be believed.....

ipfs swarm addrs | grep ip6
	/ip6/::1/tcp/4001
	/ip6/fdda:60d8:3c30:0:6ef0:49ff:fe0c:146b/tcp/4001
	/ip6/::1/tcp/4001
	/ip6/::1/tcp/4001
	/ip6/2a01:4f8:162:14d0::2/tcp/4001
	/ip6/::1/tcp/4001
	/ip6/2001:2003:58c1:fe9f::1/tcp/4001
	/ip6/::1/tcp/4001
	/ip6/::1/tcp/4001
	/ip6/::1/tcp/4001
	/ip6/::1/tcp/4001
	/ip6/fcdf:a296:afe3:7118:4135:cc0b:ff92:4585/tcp/4001
	/ip6/::1/tcp/4001
	/ip6/fc98:424c:b433:d7e2:7ee3:9541:73ff:2cdb/tcp/4001
	/ip6/::1/tcp/14001
	/ip6/fcd8:a4e5:3af7:557e:72e5:f9d1:a599:e329/tcp/14001
	/ip6/::1/tcp/4001
	/ip6/fce3:c53b:c3c5:2f54:8bb0:b6d9:898e:f140/tcp/4001
	/ip6/::1/tcp/4001
	/ip6/fcfe:eab4:e49c:940f:8b29:35a4:8ea8:b01a/tcp/4001
	/ip6/2001:1608:10:156:e::c389/tcp/4001
	/ip6/::1/tcp/4001
	/ip6/2607:f0d0:2102:88:4be:cff:fe3c:802a/tcp/4001
	/ip6/::1/tcp/4001
	/ip6/2600:3c02::f03c:91ff:fe6e:3d74/tcp/4001
	/ip6/::1/tcp/4001
	/ip6/2a01:4f8:101:10e::2/tcp/4001
	/ip6/::1/tcp/4001
	/ip6/fc17:1cec:c39d:dbc2:9e3c:25ef:62de:9ade/tcp/4001
	/ip6/::1/tcp/4001
	/ip6/::1/tcp/4001
	/ip6/fd6c:c69:60a2:bf1:5099:93ad:9b93:25f9/tcp/4001
	/ip6/::1/tcp/4001
	/ip6/::1/tcp/4001
	/ip6/::1/tcp/4001
	/ip6/::1/tcp/4001

**Comment by Kubuxu** [comment]
Addresses you see are addresses node publish themselves under. Those addresses are then heavily filtered before you try connecting with them, those are not addresses you tried or will try or connected to.

I agree that we might don't want to store localhost addresses in DHT(although it might be useful, imagine shared university machine where people run nodes on the same IP).

ULA are useful, I run whole network on ULA and this allows machines to discover themselves, remember you are not storing address that are directly needed for you, you are storing them also for other people that might be asking for them.

Another thing is that fc00::/8 is occupied by global mesh network Hyperboria.

2003::/18 is RIPE (Europe/France)

**Comment by dtaht** [comment]
Thank you for these comments.

Is there a way to custom filter out what I publish? For example, much of my ipv6 network, otherwise on public addresses, is not reachable via utp (stateful firewall, have not looked into pcp for ipv6).

Well, I kind of wish hyperboria would get themselves their own ipv6 allocation to use, instead of re-using ULA space. That would make it possible for them to publish real gateways to the internet (if they desire)

As fdXX, there is a modest probability of colliding with someone elses ULA allocations so I am resistant to seeing those in the global address space.

**Comment by Kubuxu** [comment]
You can change the swarm address in the config.

Hyperboria is not reusing ULA space, fd00::/8 is no allocated for use, and also we don't want gateways to the internet, it would defeat the purpose of the network (end to end encryption).

ULAs are designed no to collide, there are 2^56 ULA  spaces and even if there would be collision it would be just a missdial which happens all the time either way (nodes go up and down all the time) which no influence on anything.

**Comment by dtaht** [comment]
fc00 is reserved for future use. I could perhaps help with ripe/iana/etc in getting a different ipv6 address space allocated to hyperboria (routable or no). Theoretically getting your own ipv6 address space is easy, and assuming hyperboria is of reasonable size now, it would be

ULA generation is designed not to collide, but I assure you there are plenty of folk using them that start with fd00::, just as 192.168.1 is.... and with the rise of dhcpv6, we shrunk the potential collision space by a lot over the default slaac-like allocations.

Similarly "privacy" addresses are possibly stuff you don't want to export, either.

It aint up to me, obviously, I'm just noting my initial reaction to seeing so many useless ipv6 addresses show up in the table.

I sort of grok what you mean by "misdial" but do you have a formal definition of what it means in ipfs?

**Comment by Kubuxu** [comment]
Hyperboria has no chance of getting official delegation in near future, no without massive effort and relations with people inside IETF or other org, that is why we decided to use fc00::/8.

In short terms: Addresses published do no harm (unless you consider them a security problem but then it is really security by obscurity) but they are useful consider someone in same network (or maybe VPN) as you, where mDNS isn't working as it should. You still will be able to connect to him via optimal connection (local/VPN). They might be useless at first glance but for someone they are useful. It is nature of DHT that you are storing a bit of information that might not be an use for you but this means someone else might be storing and sharing a bit of information that is of use for you.

Misdial is when ipfs tries to connect to some node via some address but for some reason it didn't work, we do it concurrently and in smart ways (for example by checking if some space is even routable at all, but it isn't that simple also, that is why we do not discard address but just reorder them).

**Comment by dtaht** [comment]
I happen to be in the ietf, and going to the berlin meeting in mid july. it really shouldn't be hard to get your own address space, or so I'm told. I'll poke into it.

As for "addresses published that do no harm"...

http://arstechnica.com/security/2016/02/using-ipv6-with-linux-youve-likely-been-visited-by-shodan-and-other-scanners/

**Comment by Kubuxu** [comment]
Important note is that we are using big space `/8` (120 bits) as IP address is hash of a curve25519 public key. This is why most of us expect problems.

**Comment by dtaht** [comment]
ah, that 120 bits was unknown to me. Good luck with that.
