### ISSUE TITLE
IPFS URL

### ISSUE THREAD

**Issue by sridhar87** [ipfs/ipfs#181]
What are the best practices to use IPFS URL?

Should we rely on the IPFS URL like below to be available always, or should we use our own way to construct the URL and store just the hash of the file and access the file through our own server using the IPFS API.

https://ipfs.io/ipfs/QmburSK2Cjav26X6oGsiXwwwDXnVUUjm9i65UErRD99Z9v

After working on this for a few times, I feel IPFS is just GREAT!!! I am really feeling like this will be the future of the web storage. Great work so far. It is just mind blowing seeing this work instantly.

Thanks,
Sridhar

**Comment by Kubuxu** [comment]
@sridhar87 I opended a question under our FAQ, where we will try to formulate exhaustive answer for it.

In short terms:

* IPFS data is designed to be linked in canonical path (without schema) but support for it is not yet in browsers. In case of storage and internal representation I would use this format: `/ipfs/QmburSK2Cjav26X6oGsiXwwwDXnVUUjm9i65UErRD99Z9v`
* In browsers and other applications that use URL currently we decided to support few schemas but mainly `fs` and `web+fs` (the second one is to allow support of chrome).
 Links under those schemas do not have authority section so they look like this: `fs:/ipfs/QmburSK2Cjav26X6oGsiXwwwDXnVUUjm9i65UErRD99Z9v` (notice single slash after schema). There are browser addons that support this schema already. As not all browsers support it I am thinking of writing small piece of JS that would rewrite it to public gateway if it is not supported by browser.

Please follow up your question in our FAQ section https://github.com/ipfs/faq/issues/142

**Comment by sridhar87** [comment]
@Kubuxu  I thank you for opening a FAQ and also for answering my question.

We would start storing the hashes prepended with /ipfs/  Yeah, a javascript to rewrite the URL would be great too.
