### ISSUE TITLE
How does the `ipfs files` command (and subcommands) work?

### ISSUE THREAD

**Issue by maranomynet** [ipfs/ipfs#182]
The best I'm able to get is `Error: file does not exist`.

The `ipfs files --help` documentation is very limited and has no examples, and the online https://ipfs.io/docs/commands/ reference seems to be outdated.

How is this supposed to work? Is it a tool to update "published" ipns files, or something else?

**Comment by Kubuxu** [comment]
I tried to respond your question the best I could in our FAQ: https://github.com/ipfs/faq/issues/143

If you have any more questions about the Files API please ask there.
