### ISSUE TITLE
IPFS with Node, express and angular js

### ISSUE THREAD

**Issue by varunagarwal315** [ipfs/ipfs#186]
Extremely sorry if this is the wrong place for such a post but I had no where else to go.

I am trying to find a way to combine `ipfs` with `javascript`. 

A `GET` request to `localhost:8000` returns `index.html` which has a button on it. When clicked, a `POST` request is sent to `localhost:8000/recieve`, the data is processed and sent via an `ipfs` node using [this library](https://github.com/libp2p/js-libp2p-swarm). That node `dials` to a different node setup elsewhere, which will process the data further.

Here comes the tricky part. Based on the data processed by the second node, the user has to be shown a message. Sending information back from node2 to node1 is easy as the communication is already setup using functions from `lib p2p` but final communication with the user is something that has driven me crazy.

I know this is not an issue as such, but any and all help will be highly appreciated. Thanks in advance! Quick summary 

GET request --> index.html --> user clicks a button --> data from a form sent via POST to server setup via express --> data processed using body parser --> JSON data communicated between nodes setup by `lib p2p` --> node 2 processes data and sends response back to node 1 --> ???? --> User sees some action on index.html

**Comment by RichardLitt** [comment]
This should go in [FAQ](//github.com/ipfs/faq) or [support](//github.com/ipfs/support). The main README says this. Please reopen it there.
