### ISSUE TITLE
Is IPFS Censorship Resistant?

### ISSUE THREAD

**Issue by Miserlou** [ipfs/ipfs#187]
I started a thread on the subreddit a month about this idea and haven't had an authoritative answer yet. This is a make or break question for the network.

Here is the thread: https://www.reddit.com/r/ipfs/comments/4ngoi3/is_ipfs_censorshipresistant/

I think if IPFS is to be taken seriously, you need to draw a hard line on this issue. Both sides have valid arguments, but if you want people do develop applications for your network, this issue must be addressed.

R

**Comment by RichardLitt** [comment]
I believe that [this response](https://github.com/ipfs/faq/issues/36#issuecomment-140567411) in the FAQ repository answers this question adequately. I may be wrong; if you have more questions, I would open them in appropriate issues. Also, search: questions very similar to your question have been addressed before, and you may find an answer before needing to post here. 

In that reddit post you made, someone also pointed to that response. I would encourage you to ask questions in that GitHub thread! We do not actively moderate or answer questions on Reddit at the moment; if you have questions the best place for them is at [ipfs/faq](https://github.com/ipfs/faq/issues/).

**Comment by RichardLitt** [comment]
I would also check out this thread, [comparing IPFS to Freenet](https://github.com/ipfs/faq/issues/18). 

Closing this, as I believe it has been answered here, and you know where to ask more questions if you have some. Let's move this discussion to the FAQ.

**Comment by RichardLitt** [comment]
Actually, reopening to make sure you feel that your issue is answered. Let me know!

**Comment by martinvahi** [comment]
I know that my current post is out of topic here, but since this thread seems to be a general discussion thread, then I would like to propose that the IPFS is made less dependent on the specific version of the Go language. The Go is a hell to compile, because it depends on so many libraries from the operating system, which means that practically the only people, who are able to compile Go are the packagers, who practically maintain a package collection specific fork of Go.

Thank You for reading my comment. :-)

**Comment by thisconnect** [comment]
@martinvahi I found it hard to compile go too, as you need to have an older go version to compile the current one. This works for me on Linux and OS X https://gist.github.com/thisconnect/984634718308a54e97b90602584cc1af 

(sorry off topic)

**Comment by RichardLitt** [comment]
@martinvahi and @thisconnect You're right, that is off topic. I would suggest you open a new issue in github.com/ipfs/faq or, if you have actionable suggestions, in github.com/ipfs/go-ipfs. 

Closing this as it is old.
