### ISSUE TITLE
Is there any way to check the "health" of an ipfs file?

### ISSUE THREAD

**Issue by traverseda** [ipfs/ipfs#191]
With torrents, you can generally get the number of seeders. Does ipfs have a similar mechanism? Can ipfs have a similar mechanism?

**Comment by RichardLitt** [comment]
Hey @traverseda. I would suggest opening this in github.com/ipfs/faq: it will be seen faster, and then will be viewable by others. Let me know if you would like help opening an issue there.

**Comment by traverseda** [comment]
https://github.com/ipfs/faq/issues/153
