### ISSUE TITLE
Idea: IPDB - Database

### ISSUE THREAD

**Issue by mkg20001** [ipfs/ipfs#192]
IPDB Idea:
 - local: a database on the client
 - public: a database in the network
 - Peer: a database shared with a specific Peer
Blocks:
 - public-database
 Contains links to databases and signed change/add requests from Nodes

- database
  Contains links to tables

- table
  Contains Blobs (links to others hashes/files) or Strings/Integers/...

Any App could use /ipdb/APP/local or public to load entrys and execute querys
```
/ipdb/APP/public/PEER <-- public database of PEER
/ipdb/APP/PEER <-- shared with PEER
/ipdb/APP/local <-- local database
```

After a table is changed a new table Block is created (or something like "changelogs") by the node and a change request for the public database is created.

An alternative would be a mongoDB like structure instead of tables, which would be easier.
both tables and (whatever they are called in mongoDB) in parralel would be also an idea.

Feel free to comment suggestions, it's just a idea.
Sorry for my bad english.
Is this even the right repo to post this?

**Comment by whyrusleeping** [comment]
@mkg20001 I think this would be best discussed over in ipfs/notes (where this will be a totally valid and welcome issue). 

Some related things to take a look at first:

- [orbit db](https://github.com/haadcode/orbit-db)
- [IPDB](https://ipdb.foundation/)

**Comment by mkg20001** [comment]
moved: https://github.com/ipfs/notes/issues/150
