### ISSUE TITLE
HTTP request header 'Accept-Ranges' does does not respond in some case. 

### ISSUE THREAD

**Issue by border0464111** [ipfs/ipfs#194]
I was trying to embed some video and in a webpage, They work well if I call them directly but not working once imbeded if they are not on my local cache.

So I narrowed the problem to a point where the following query (wich replicate query made by my webpage) will never receive a response and hang eternaly:

curl 'http://127.0.0.1:8080/ipns/QmdyyqsCJCyV4swTu7GsuCKfD3kZkBkiRriDi1KiWFzk7m/100K%20Subscribers%20Special%20Compilation%20_%204H%20Party%20Music%20_%20EDM,%20NCS,%20Dubstep-iJ05N8pCI0E.webm' -H 'Referer: http://127.0.0.1:8080/ipfs/QmVMML5x3ZhDCA9zNyWmm9dXvKJ9tMh7PaHWYSDjTLnTRn/' -H 'Accept-Encoding: identity;q=1, *;q=0' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36' -H 'Range: bytes=390496256-' --compressed

If I change to 'Range: bytes=9000-' or remove it completely. The data will start to flow in. 

Im supposing file lenght is smaller then 390496256. ( But due to an other bug, Im sudently unable to resolve de IPNS anymore... ) 

In any case, what ever is the reason for this. Gateway should return HTTP 416 status code(Requested Range Not Satisfiable) instead of hanging.

**Comment by RichardLitt** [comment]
Hey @border0464111, thanks for the issue. This should probably be in ipfs/support, where it will be dealt with faster than here, and where it will be useful for others who may run into the same problem. Can you reopen it there? Thank you.

**Comment by border0464111** [comment]
done https://github.com/ipfs/support/issues/35
