### ISSUE TITLE
Idea for the standardization of otherwise proprietary hash formats

### ISSUE THREAD

**Issue by ConsciousCode** [ipfs/ipfs#195]
At the present moment, unless something's changed since I last checked, IPFS hashes blocks along with their links. Some have cited this as a problem, as it renders clients unable to predict data hashes without link data, but the developers have (correctly) expressed that this edge data must be part of the hash because link and payload data are part of the same structure and thus can change the semantics. Here, though, I propose a compromise:

Separate blocks and links as separate files within IPFS. This is to say, have one hash dedicated to the payload of a block and another dedicated to the filename:address map file (which should have a canonical format such that conforming link files with the same semantic mapping have the same hash). The pros and cons are as follows:

Pros
* Decouples data from its relationships with metadata
* Universality/generality
* Programs using IPFS don't need an API to predict the hash of data to be submitted, don't need to know the exact link format, and don't need to bake link data into their content
* Lower space usage over the long term (files with the same content but different links need only store the data and link files, and data will tend to be repeated and thus have intrinsic redundancy in the network by virtue of shared file formats)
* Other than directories and merkle trees, the link structure isn't especially useful to most programs as they won't know their intended semantics without knowing the data's format

Cons
* The address format will have to be expanded to allow link files to be associated with ordinary data
 * Alternatively, links could be removed from their special place in the protocol in favor of standardized formats which have links as part of their content (e.g. directories), though this destroys universal iterability
   * The iterability of all IPFS file structures regardless of format has some utility and discoverability properties, but the vast majority of structures with extensive use of the feature will be either directories or merkle trees, which can have their own file format

So, what do you think?

**Comment by RichardLitt** [comment]
Hey @ConsciousCode, thanks for posting this. 

I would put this in github.com/ipfs/notes: that is where you are most likely to get the most traction on it. Another idea would be to put it in ipfs/faq, but I think that this may warrant a larger discussion than just a frequently asked question. 

Please reopen the issue there; ipfs/ipfs isn't used for discussions, at the moment. Thank you.

**Comment by jbenet** [comment]
@richardlitt maybe we should remove the issues feature on this repo

**Comment by RichardLitt** [comment]
That would work well, but we want to be able to have our own issues. I need to signpost that the issues aren't used, and actively close the other ones. Will get to it when I have some more time.

**Comment by ConsciousCode** [comment]
Oh sorry, is there an official fork I should be following instead?
