### ISSUE TITLE
Question: Cross Site Isolation

### ISSUE THREAD

**Issue by exyi** [ipfs/ipfs#200]
Hi,
I could not find how to make site hosted at IPFS isolated from others, so they can not read my cookies and data local storage. Http solves this by cross domain isolation , but if I understand it correctly, IPFS sites are only presented as different files on the same domain.
I'd also like protect the API at the node (like who are my peers, mounting directory) from being seen by random websites.
How is that solved, or is this a feature?

**Comment by lidel** [comment]
Isolation when using http gateway is an open issue. 

There is ongoing discussion about providing per-page [Suborigins (w3c standard draft)](https://w3c.github.io/webappsec-suborigins/) in the http gateway: https://github.com/ipfs/go-ipfs/issues/651

**Comment by exyi** [comment]
@lidel Thank you for quick response, I'll look at these issues.
