### ISSUE TITLE
The docker command is not working unless I add -i parameter

### ISSUE THREAD

**Issue by RyanZhu1024** [ipfs/ipfs#202]
I ran the command from the docker documentation and I got error: ipfs repo not found, please run `docker init` first. I'm confused by this message as I can't even start the docker, how can I run `docker init`. So after some other try, I happened to add `-i` parameter and then it works. I don't know why, but at lease it's working. Can someone explain it and maybe update the documentation from the docker up?

**Comment by RichardLitt** [comment]
Hi @RyanZhu1024, thanks for the issue. This may get better traction in github.com/ipfs/support. Do you mind reopening the ticket, there?

**Comment by RyanZhu1024** [comment]
@RichardLitt Sure.

**Comment by RichardLitt** [comment]
Reopened in https://github.com/ipfs/support/issues/37.
