### ISSUE TITLE
IPFS stuck with large file

### ISSUE THREAD

**Issue by hongcoiner** [ipfs/ipfs#204]
Anyone can help try this large file(1.07G) and tell why it's forever stalling at a point after every xxM bytes transferred?

**QmaAg5484aGuTZSGCFyoz3c81cf3XraCgKrrkCyQMinspQ**

No "Block" message found in log but repeating dhtXXXX events after stalling:

...........
":"dhtSentMessage","message":{"key":"QmNQQjXejrWTqcJVn4VvoifyeHVsf2RhiSYYthg3Vr9pcK","type":"ADD_PROVIDER"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","session":"1bf63ad4-e48c-4700-8463-4224cbe9b5fe","system":"dht","time":"2016-09-25T04:12:37.777068986Z"}
{"event":"dhtSentMessage","message":{"key":"QmNQQjXejrWTqcJVn4VvoifyeHVsf2RhiSYYthg3Vr9pcK","type":"FIND_NODE"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:12:37.778232241Z"}
{"event":"updatePeer","peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:12:37.961336935Z"}
{"event":"dhtReceivedMessage","message":{"key":"","type":"FIND_NODE"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:12:37.961603242Z"}
{"event":"dhtSentMessage","message":{"key":"QmNR6CfCkGgXozjgrcNeZgBWhBnJXgJWRkGwF6grWU5kUq","type":"ADD_PROVIDER"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","session":"1bf63ad4-e48c-4700-8463-4224cbe9b5fe","system":"dht","time":"2016-09-25T04:13:10.509298528Z"}
{"event":"dhtSentMessage","message":{"key":"QmNR6CfCkGgXozjgrcNeZgBWhBnJXgJWRkGwF6grWU5kUq","type":"FIND_NODE"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:13:10.518546515Z"}
{"event":"updatePeer","peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:13:10.693282081Z"}
{"event":"dhtReceivedMessage","message":{"key":"","type":"FIND_NODE"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:13:10.693345958Z"}
{"event":"dhtSentMessage","message":{"key":"QmNRwE1239t9qpB31hY288SpkA4jyAjB4LhaaZPvMNXFCD","type":"ADD_PROVIDER"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","session":"1bf63ad4-e48c-4700-8463-4224cbe9b5fe","system":"dht","time":"2016-09-25T04:13:29.838782603Z"}
{"event":"dhtSentMessage","message":{"key":"QmNRwE1239t9qpB31hY288SpkA4jyAjB4LhaaZPvMNXFCD","type":"FIND_NODE"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:13:29.854732199Z"}
{"event":"updatePeer","peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:13:29.896747759Z"}
{"event":"dhtReceivedMessage","message":{"key":"","type":"FIND_NODE"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:13:29.911719038Z"}
{"event":"updatePeer","peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","session":"1bf63ad4-e48c-4700-8463-4224cbe9b5fe","system":"dht","time":"2016-09-25T04:13:33.127104231Z"}
{"duration":3661082,"event":"handleGetProviders","key":"QmPaF1L4YdNRUiKoxPUSS9xpbk9oPjZApRY1YUtWdrp5im","peer":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","session":"1bf63ad4-e48c-4700-8463-4224cbe9b5fe","system":"dht","time":"2016-09-25T04:13:33.131046997Z"}
{"event":"dhtSentMessage","message":{"key":"QmNSEK7NA7i1GKFn4NkFmmpzaetQh52Lv4giWKYHpFWZB6","type":"FIND_NODE"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:13:51.313737929Z"}
{"event":"dhtSentMessage","message":{"key":"QmNSEK7NA7i1GKFn4NkFmmpzaetQh52Lv4giWKYHpFWZB6","type":"ADD_PROVIDER"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","session":"1bf63ad4-e48c-4700-8463-4224cbe9b5fe","system":"dht","time":"2016-09-25T04:13:51.327385627Z"}
{"event":"updatePeer","peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:13:51.42502523Z"}
{"event":"handleGetProvidersBegin","peer":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","session":"1bf63ad4-e48c-4700-8463-4224cbe9b5fe","system":"dht","time":"2016-09-25T04:13:33.127439962Z"}
{"event":"dhtReceivedMessage","message":{"key":"","type":"FIND_NODE"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:13:51.425168232Z"}

**Comment by whyrusleeping** [comment]
Hey @hongcoiner, Could you move this issue to the https://github.com/ipfs/support repo? This repository is for discussion and issues with the ipfs protocol itself.

Thanks!

**Comment by hongcoiner** [comment]
ok, will do
