### ISSUE TITLE
IPFS daemon behind (corporate) firewall

### ISSUE THREAD

**Issue by pyhedgehog** [ipfs/ipfs#209]
I'm not sure that this is not implemented already, in this case this should be seen as request for documentation. :-)

I want to run ipfs node (at least to cache accessed entries) on computer in LAN that has no direct access to internet (no inbound connections at all, outbound connection only via restrictive proxy - ports 80 and 443 only). I have several options to connect outside available:
 1. Mentioned restrictive http proxy.
 1. Tor (socks and privoxy).
 1. Socks via ssh tunnel to home computer (via tor).

How should I configure ipfs to work in such environment?

**Comment by RichardLitt** [comment]
Hi @pyhedgehog, thanks! This is a good question. It may belong in [ipfs/faq](//github.com/ipfs/faq) or in [ipfs/support](//github.com/ipfs/support). Could you reopen it there?

**Comment by pyhedgehog** [comment]
Already exists ipfs/support#32
But it's not answered for almost half a year!

**Comment by RichardLitt** [comment]
I pinged some people on IRC. Let's get an answer for you sooner. Thanks.

**Comment by RichardLitt** [comment]
@pyhedgehog There's been some response over on ipfs/support#32. For now, I would direct you there. We're also trying out ipfs.trydiscourse.com - this would be a great place to put your question, actually, as a lot of the devs are looking at it at the moment. 

For now, closing this issue. Thanks.

**Comment by pyhedgehog** [comment]
@RichardLitt, there are not meaningful response in ipfs/support#32.

 1. "ipfs does not use http"? http proxy has CONNECT method.
 2. What about socks configuration? How it should be done? What will be correct format instead of `/ipv4/127.0.0.1/tcp/9050/socks/longandunmemorizablename.onion/QmNODEID`?

**Comment by RichardLitt** [comment]
@pyhedgehog I hear you. Thanks for posting those questions there; I hope we're able to answer those for you (I would, of course, if I knew the answers. I don't.) 

Either way, though, this repository is not the right place to ask these questions.

**Comment by pyhedgehog** [comment]
I've copied questions to support repository.

**Comment by GitDoggo** [comment]
Why is this issue closed? Do we have a way to go around proxys?
If I follow the links it's "*Issue moved to [there]*" > "*Issue moved to [there]*" > [This page](https://discuss.ipfs.io/t/cant-find-peers-behind-proxy/514) which gives no additionnal information.

Is the answer basically "it doesn't interfere with proxy"? Because it's what I managed to understand from the issues, but it's not true.

**Comment by Stebalien** [comment]
@GitDoggo we've moved support questions/discussions to the forums. However, it looks like this was also a feature request (socks proxy support).

I've filed an issue (https://github.com/libp2p/go-libp2p/issues/286). For now, the only solution is to handle this *outside* of ipfs. There are VPN-like tools that will tunnel all OS traffic through a socks proxy (e.g., https://code.google.com/archive/p/badvpn/wikis/tun2socks.wiki). However, I can't find any good, mature ones (although they must exist somewhere).

**Comment by GitDoggo** [comment]
@Stebalien Thanks for your answer.
But sadly, VPN-like tools are blocked by my company proxy (Anonymizing Utilities), I could be in big trouble for using them, and I assume it's the same for most companies.

**Comment by Stebalien** [comment]
This would be a "vpn-like" tool that would route all traffic *through* the corporate (socks) proxy so I doubt they'd have an issue with it. Basically, instead of configuring each application to use the proxy independently, you'd configure the the OS itself to use the proxy.
