### ISSUE TITLE
Python implementation?

### ISSUE THREAD

**Issue by maliabadi** [ipfs/ipfs#21]
i'd be into working on one. maybe a python implementation of a smaller submodule. ipfs-datastore?

**Comment by Aaron1011** [comment]
I'd also be interested in working on this.

**Comment by jbenet** [comment]
Hello, the https://github.com/jbenet/go-ipfs/ implementation is the "reference". We need to pull out the protocol descriptions into a separate package.

**Comment by JulienPalard** [comment]
Clearly, this project needs documentation about its protocols, imbrincations, dependencies, etc... not just a "reference implementation".

**Comment by jbenet** [comment]
@JulienPalard naturally. The first version has been in development and protocols _have_ changed or been added during. We're finally reaching protocol stability and it is _now_ a good time to synthesize a spec. As i stated above:

> We need to pull out the protocol descriptions into a separate package.

We haven't gotten to it yet, but if you'd like to help it will certainly go faster.

**Comment by bmcorser** [comment]
@jbenet Could there be an issue for writing up the IPFS spec? Perhaps containing specific information about where the protocols are implemented and where they should be written up ...

@maliabadi @JulienPalard @Aaron1011 should we make a GitHub organisation or something?

**Comment by Aaron1011** [comment]
Sure! Sounds good to me.

**Comment by bmcorser** [comment]
71 days later, I have created the organisation.

I looked at ipfs.io again today when telling people about the project and saw things are coming along, so it might be an opportune moment to look at the Python implementation.

I've invited people from this issue who expressed interest and created a repo [`ipfs`](https://github.com/python-ipfs/ipfs) to get the issue tracker. I've added an issue there https://github.com/python-ipfs/ipfs/issues/1 to talk about first steps.

**Comment by jbenet** [comment]
@bmcorser why not do it inside the `ipfs` org? we can setup a `py-ipfs` team inside it, like we've setup the `go-ipfs` team and we're going to setup the `node-ipfs` team. there's a lot of other tools that will be cross impl (like test suites, repo specs, scripts, and so on) that we can all collab on that will be more findable by users there. 

Ok, I've created a team and invited you. want to drop by on `#ipfs` on irc and discuss?

**Comment by jbenet** [comment]
Also, the specs are underway here: https://github.com/ipfs/specs/ i'm allocating more and more time to this. (development, debugging, infra, admining, etc all have cut into spec time of late :( )

**Comment by bmcorser** [comment]
@jbenet cool, thank you. Would you invite @maliabadi @JulienPalard and @Aaron1011 too? I feel a bit intimidated on my tod.

I'll leave the other org open for a few days to avoid any confusion.

**Comment by jbenet** [comment]
Great! i've invited everyone and made https://github.com/ipfs/py-ipfs 

> I feel a bit intimidated on my tod.

tod?

**Comment by jbenet** [comment]
I'll close this
