### ISSUE TITLE
ipfs mount

### ISSUE THREAD

**Issue by raedok** [ipfs/ipfs#210]
OS X - macOS Sierra (10.12.1)

After battling fuse-version because go kept saying $GOPATH is not set even though I set it and I ran the download command manually which downloaded and installed fuse-version in the bin folder of the $GOPATH I had set, I ended up copying the installed binary to /usr/local/bin. That made ipfs mount no longer try to install fuse-version however a peculiar message has come instead:

> localhost:~ raedok$ ipfs mount
> Error: OSXFUSE version 3.5.3 not supported.
> 
> OSXFUSE versions <2.7.2 are known to cause kernel panics!
> **Please upgrade to the latest OSXFUSE version.**
> It is recommended you install it from the OSXFUSE website:
> 
> 	http://osxfuse.github.io/
> 
> For more help, see:
> 
> 	https://github.com/ipfs/go-ipfs/issues/177

Now I understand why version < 2.7.2 is a problem, however I am running the last version of OSXFUSE.

Is there another version of OSXFUSE that I should install? Something like 2.8.something?

Also, as a side note I while trying to figure out a way around fuse-version I tried using **ipfs config DontCheckOSXFUSE true** and I had to manually modify ~/.ipfs/config because the last version of ipfs requires DontCheckOSXFUSE to have a string value instead of a boolean one (had to make it "true" instead of true -- even though I did try ipfs config DontCheckOSXFUSE "true")

**Comment by VictorBjelkholm** [comment]
Thanks for the report @raedok! I think this would have been better suited in ipfs/go-ipfs, but we already have a open issue about this (https://github.com/ipfs/go-ipfs/issues/3410) and also a open pull request (https://github.com/ipfs/go-ipfs/pull/3413). So I'll close this for now.

Would be nice if you could open an issue in go-ipfs regarding the string vs boolean value of `DontCheckOSXFUSE` in go-ipfs instead.
