### ISSUE TITLE
Common-port-listening-nodes needed in bootstrap to combat the great firewall of $(my local coffee shop)

### ISSUE THREAD

**Issue by mib-kd743naq** [ipfs/ipfs#221]
This is specifically related to https://github.com/ipfs/ipfs/issues/111#issuecomment-150186286 and https://github.com/ipfs/ipfs/issues/111#issuecomment-150301573.

As of the opening of this ticket a fresh install/init of go-ipfs looks like this:
```
~$ ipfs bootstrap
/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
/ip4/104.236.151.122/tcp/4001/ipfs/QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx
/ip4/104.236.176.52/tcp/4001/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z
/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM
/ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64
/ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu
/ip4/162.243.248.213/tcp/4001/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm
/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd
/ip4/178.62.61.185/tcp/4001/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3
```

Note that every single host is declaring port `4001`. I think by default there got to be at least one ( preferably several ) nodes listening on `tcp/80`, `tcp/443` and `tcp/53`.

This will go a long way for folks who are just starting to play with IPFS to not go "eh... it doesn't work" and move on to something else.

**Comment by whyrusleeping** [comment]
I support this, @lgierth wanna make this an infrastructure ticket so we can move forward with it?

**Comment by VictorBjelkholm** [comment]
Open issue in ipfs/infrastructure instead.
