### ISSUE TITLE
ERROR: dht: checking dht client type: &errors.errorString{s:"EOF"} notif.go:38

### ISSUE THREAD

**Issue by st5ryertfdasfrgttgdrgs** [ipfs/ipfs#223]
I get that error after starting `ipfs daemon`

**Comment by lgierth** [comment]
I've seen this too the other day. :+1: Would you mind filing this as in issue in the ipfs/go-ipfs repo?

**Comment by sere4tegdd** [comment]
@lgierth if you keep the deamon running, you'll see other ERRORs too... I see errors with `bitswap` and `commands/h`

**Comment by RichardLitt** [comment]
Thanks for logging this. As noted in the Issue and by @lgierth, this doesn't belong in this repo - ipfs/ipfs doesn't concern the go-ipfs implementation. Please open an issue in ipfs/go-ipfs or in ipfs/support. Thank you!
