### ISSUE TITLE
How can i send a data to specific peer if i already knew his peer id?

### ISSUE THREAD

**Issue by sagar117** [ipfs/ipfs#225]
PLEASE READ THE FOLLOWING BEFORE CREATING AN ISSUE

This repo exists just to provide an overview of the entire ipfs project and
ecosystem.  If you are about to file an issue about a certain implementation of
ipfs (for example, go-ipfs) Please instead file it in the appropriate location:

For actionable issues pertaining to BUGS in GO-IPFS, create an issue over at:
https://github.com/ipfs/go-ipfs/issues

For SUPPORT issues with any ipfs implementation, go to:
https://github.com/ipfs/support

For QUESTIONS about ipfs in general, go to: 
https://github.com/ipfs/faq

For anything else, please take a look at the project directory on this repos
README.md to find the appropriate location for your issue.

**Comment by RichardLitt** [comment]
This belongs in support, or in FAQ. Please read the template provided above, in your issue. Thank you!
