### ISSUE TITLE
Is it possible to see which IPs are hosting a particular IPFS address?

### ISSUE THREAD

**Issue by LRonHubs** [ipfs/ipfs#251]
What function can be used to see all of the IP addresses hosting a particular IPFS file?

**Comment by nannal** [comment]
ipfs dht findprovs $addr

**Comment by VictorBjelkholm** [comment]
This was also asked on our forum (by the same user) and has more answers: https://discuss.ipfs.io/t/how-to-view-the-ip-addresses-hosting-a-particular-file/145
