### ISSUE TITLE
Application: ipjson

### ISSUE THREAD

**Issue by voltrevo** [ipfs/ipfs#252]
How about a single interplanetary json object?

Basically, this is the filesystem of ipfs except directories/files are replaced with json blobs - that is, every json blob has an ipfs address, and json blobs can link to other ipfs addresses.

So /ipfs/ is analogous to the ipjson root object, which is like a json object with non-enumerable keys and maps hashes to the json structure corresponding to that hash. The hashes for json would have to be defined in a way that is built up as a tree structure like the ipfs filesystem as opposed to something trivial like `hash(JSON.stringify(obj))` which would squander the potential here. This would allow (potentially huge) json documents to be efficiently versioned and distributed, since a small change would propagate up the tree leaving most of the merkle nodes unchanged, the same way this happens if you modify a file in a big directory structure.

Afaict, this wouldn't be separate from ipfs, it should map onto the ipfs primitives quite well for building up this structure. The implementation would just have to interpret the binary blobs that it retrieves from ipfs differently, so that it can decode what it gets back into a mixture of raw json (some binary encoding like msgpack) and links to more json.

**Comment by flyingzumwalt** [comment]
You're describing [IPLD](https://github.com/ipld/specs/tree/master/ipld). IPFS is designed to handle any sort of data, not just files and directories. IPLD is the abstract model that lets us do it. It's compatible with JSON-LD.

**Comment by diasdavid** [comment]
@voltrevo check out these examples -- https://github.com/ipfs/js-ipfs/tree/master/examples/traverse-ipld-graphs -- on the js-ipfs repo, they show how to use JSON, Protobufs, Cbor and more!

**Comment by diasdavid** [comment]
@voltrevo hope the answers provided were useful enough. I'm closing this issue but you are welcome to continue this conversation on our discussion forum at https://discuss.ipfs.io/
