### ISSUE TITLE
IPFS retrive files

### ISSUE THREAD

**Issue by deepthik-r** [ipfs/ipfs#258]
Hi ,
I am creating one use case where i need to upload all kinds of files(like .pdf,.ppt,.docx,.xl).
I am able add and get files. but ppt,xl,docx file links downloading zip files which contains different folder structure. 
Can anyone help in downloading all these kinds of files from ipfs?

**Comment by VictorBjelkholm** [comment]
I left a answer here: https://discuss.ipfs.io/t/retrive-docx-and-ppt-via-http-returns-zip-file/713

Please only post in one place when having general questions (ideally on discuss.ipfs.io)
