### ISSUE TITLE
Incorrect instruction on ipfs website

### ISSUE THREAD

**Issue by alphaCTzo7G** [ipfs/ipfs#260]
I noticed that there is an incorrect instruction here: https://ipfs.io/blog/22-run-ipfs-on-a-vps/

Towards the bottom, it instructs users to pin the hash using:

ipfs pin ls | grep QmT78zSuBmuS4z925WZfrqQ1qHaJ56DQaTfyMUF7F8ff5o

The correct command probably should be:
 
ipfs pin add QmT78zSuBmuS4z925WZfrqQ1qHaJ56DQaTfyMUF7F8ff5o

Is this correct?

**Comment by alphaCTzo7G** [comment]
Created pull request here.. 

https://github.com/ipfs/blog/pull/124

**Comment by VictorBjelkholm** [comment]
Looks correct to me, thank you! Merged the linked PR
