### ISSUE TITLE
Combining IPFS and Bitcoin?

### ISSUE THREAD

**Issue by pruflyos** [ipfs/ipfs#263]
### Why? 
Currently every Bitcoin node must maintain a **FULL COPY** of the Bitcoin blockchain. However, if for example every Bitcoin block could be retrieved under it's blockhash via IPFS as well (e.g. in JSON format),  people could develop decentralized/distributed Bitcoin applications (e.g. a block explorer), that doesn't need a local Bitcoin Full Node running, but can instead retrieve the desired blocks via IPFS.

**Problem with different hashing algorithms of IPFS content and Bitcoin blocks**
I realize that every IPFS content hash starts with `Qm...` whereas a Bitcoin block starts with a lot of zeros. So it would be necessary to introduce the Bitcoin hash verification algorithm to IPFS so Bitcoin blocks could be addressed in IPFS by their Bitcoin hash (with a prefix): `/ipfs/BTC00000000000000000123acc5178e5332b6204442622e6adbd4fa7558980babb4`

**Comment by jsmith-dev** [comment]
Wild.

Following this thread.

**Comment by magik6k** [comment]
This is pretty much exactly what [IPLD](https://github.com/ipld/ipld) is made for, there is even BTC parser in progress among others: https://github.com/ipfs/go-ipld-btc.

You can interact  with IPLD using `ipld dag` commands. The support is still experimental/in progress and there is no built-is BTC support as of now but these things are being worked on actively.

**Comment by dali99** [comment]
This is the plan for ethereum swarm as well

**Comment by diasdavid** [comment]
We know have support for BTC and ETH in go-ipfs and ETH support in js-ipfs. You can learn how to explore IPLD graphs in the following examples https://github.com/ipfs/js-ipfs/tree/master/examples/traverse-ipld-graphs

Help us get BTC support for js-ipfs as well! :) 

Closing this issue for now, if you would like to continue discussing it, please open a thread at https://discuss.ipfs.io/
