### ISSUE TITLE
Implementation Status Table - PubSub

### ISSUE THREAD

**Issue by diasdavid** [ipfs/ipfs#270]
- [ ] PubSub
  - [ ] list out HTTP endpoints based on http-api-docs (and not http-api-spec)
  - [ ] Add table for CLI
  - [ ] Review and update status in all the endpoints

**Comment by diasdavid** [comment]
@hacdias would you mind getting this one?

**Comment by hacdias** [comment]
Yeah, I can check this and the others you've assigned to me.
