### ISSUE TITLE
Question: If any nodes shutdown, does it mean some files disappear?

### ISSUE THREAD

**Issue by dtco-kimi** [ipfs/ipfs#272]
I saw the introduction 'zero duplication'. Does it mean no any backup on ipfs network? If my drive is damaged or WannaCray encrypts my files, the contents of files on my node will be lost forever, right? 
We plan to use ipfs in our private chain, but we have to make sure no any data loss even if any one of nodes crashes/is compromised.
Thanks.

**Comment by Guitlle** [comment]
In order to avoid loss of information, you should use redundancy strategies, which means, more than one node should have your data. The more redundant your data in different nodes is, less probability of losing your information.

**Comment by diasdavid** [comment]
Closing this issue for now, please open the question in our forum at https://discuss.ipfs.io/
