### ISSUE TITLE
Can I use the webui from remote?

### ISSUE THREAD

**Issue by myqq0000** [ipfs/ipfs#273]
Hi there. I installed and ran the ipfs on a VPS. And I change the config so that I can use it from remote. (Such as my own device).
My config is like that:
```
"Addresses": {
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001"
    ],
    "API": "/ip4/0.0.0.0/tcp/5001",
    "Gateway": "/ip4/0.0.0.0/tcp/8080"
  }
```
I change the `127.0.0.1` to `0.0.0.0`
So that I can use command to visit the IPFS on a VPS.
But when I try to visit the webui through` serverip:5001/webui`, it shows nothing...
Can you tell me how to solve it? Or maybe it's not possible to use webui from remote? 
THANKS~

**Comment by lgierth** [comment]
Please don't open up the API port 5001 to the public -- it's a huge security risk. Use an SSH tunnel instead, e.g. `ssh -L 5001:localhost:5001 user@serverip`. This will give you a local port 5001 forwarded to the actual API port, but without exposing it to the public.

**Comment by diasdavid** [comment]
Closing this issue. If you still have more questions, please open a thread on https://discuss.ipfs.io/. Thanks!

**Comment by myfingerhurt** [comment]
For the reference see 
https://github.com/ipfs-shipyard/ipfs-webui/issues/594#issuecomment-417922174

**Comment by trancephorm** [comment]
I have the same problem. Thing is if we change from 127.0.0.1 to something like 192.168.1.10, we're opening it just to local network, and it's not much of a security risk. I see now issue is opened about this, was this solved at all - can we access webui from some other than local machine?

**Comment by Stebalien** [comment]
https://github.com/ipfs/ipfs/issues/273#issuecomment-339696462
