### ISSUE TITLE
pubsub sub provides no response

### ISSUE THREAD

**Issue by rmnoff** [ipfs/ipfs#280]
Using the v0.4.10 IPFS I am unable to use pubsub.. Looks like it brings no response, while using subscription.
    `ipfs pubsub sub foo`

there is no response and it stays forever.
how should it work? What should I do? Should it have a timeout, so users would at least have some response.

**Comment by diasdavid** [comment]
Please open support issues on https://discuss.ipfs.io/

//cc @whyrusleeping
