### ISSUE TITLE
Advertise the weekly All Hands calls in the readme and on ipfs.io website

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/ipfs#283]
It's come to my attention that the readme doesn't advertise the All Hands calls. It's only advertised in the readme of https://github.com/ipfs/pm We should advertise it more prominently on this repository's readme and on the ipfs.io website.

**Comment by daviddias** [comment]
//cc @ipfs/community-wg

**Comment by pkafei** [comment]
Good idea. I also think we ought to advertise the All Hands Call in the issues section.

Where exactly will we put the All Hands Call reminder on the website? Should we add a notification bar on the day of the call? At the very least we can mention the All Hands call in [community page of the IPFS docs](https://docs.ipfs.io/#community).
