### ISSUE TITLE
webui can't bring up

### ISSUE THREAD

**Issue by udtrokia** [ipfs/ipfs#298]
ERROR     swarm2: failed to reset connection deadline after setup: set tcp 192.168.0.106:4001: use of closed network connection swarm_dial.go:406

**Comment by Stebalien** [comment]
Please file an issue on the webui repo (https://github.com/ipfs-shipyard/ipfs-webui) details about what you were trying to do at the time, where you saw the error, what version of go-ipfs you're using, etc.
