### ISSUE TITLE
Node Implementation

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipfs#3]
The first implementation, in Node is at https://github.com/jbenet/node-ipfs

Will be used for many of the Demos in #2.

**Comment by NodeGuy** [comment]
A friendly question:  In a containerized world, is it a better use of developer resources to re-implement IPFS in Node.js or to provide a thin Node library which communicates with the canonical implementation?

**Comment by kofalt** [comment]
> I'm a container dev
> In a container wor-rrld
> Life in cgroups
> It's ... fruity loops!

*cough* Sorry.

I seem to recall that one of the IPFS team's goals was to be able to make IPFS reads from the browser.

**Comment by NodeGuy** [comment]
Thanks for the song!  Who says engineers aren't creative?

I would love to see a version of IPFS hosted in the browser, but that's a different animal than a Node.js implementation.

**Comment by jbenet** [comment]
@kofalt :+1:  :heart: 

@NodeGuy though i started with Node, we switched to [Go](https://github.com/jbenet/go-ipfs). But i really want to get a version of IPFS that works in node/iojs and the browser. 

I was talking with @mafintosh about this earlier today, and it's going to be _much_ easier to make go-ipfs usable from node -- this means:
-  make it installable from npm (maybe using prebuilt binaries) 
-  a module to launch + control the ipfs daemon from node
-  use @mappum's [ipfs-api](https://www.npmjs.org/package/ipfs-api), which you can use to do everything through the ipfs API (it needs a readme).

So we're pretty close to this! It may be doable in a few days. Just need people interested enough to help me get it over the hump.

Second, making a full implementation of ipfs in node is a larger beast but very much worth doing. there's two levels to this:
- make an ipfs.js impl that conforms to the protocol (this depends on having a concrete spec, which i've started on and can make available soon)
- make the impl able to expose an http api that conforms to go-ipfs's http api. that way any frontend (webui or go-ipfs cli tool or others) can use it to control a node implemented in any language. (this depends on having a concrete api spec, which is worth having soon as it will document go-ipfs anyway)

Feel free to come discuss on irc (#ipfs on freenode) -- or keep talking here. We're interested in helping all of these efforts.

**Comment by mafintosh** [comment]
summoning @sorribas / @watson because they might be interested in helping out

**Comment by watson** [comment]
@jbenet sounds like a fun project :) I think it would be pretty easy to create a thin node wrapper that just talks to the daemon if that was the first step you had in mind? I could give it a go if you'd like?

**Comment by jbenet** [comment]
@watson yeah, please do!

**Comment by NodeGuy** [comment]
@watson it looks like that's what @mappum has started with his [node-ipfs-api](https://github.com/mappum/node-ipfs-api), yes?  Are you planning on collaborating with him or on starting a new project?

A bit about me:  I'm working with [Eris Industries](https://erisindustries.com/) and we're pretty excited about IPFS so I expect my involvement to increase over time.

**Comment by martindale** [comment]
I'd like to help out with this!  I'm still grokking the whitepaper for the protocol definition, but would appreciate some guidance on actual implementation.

**Comment by whyrusleeping** [comment]
@martindale our go implementation is currently the 'reference' implementation, and we are working on more detailed specs over at [ipfs/specs](http://github.com/ipfs/specs), stop by our irc channel, #ipfs on freenode and chat sometime!

**Comment by jbenet** [comment]
update:

- https://www.npmjs.com/package/ipfs-api now has a readme + examples. (thanks @travisperson)
- we need a `ipfs-deamon-ctl` that starts, stops, manages any ipfs node (regardless of impl language) as discussed above.
- after that, we'll make an atom-shell packaged node so it's trivially easy to install + keep running ipfs nodes.

**Comment by watson** [comment]
@jbenet sorry for being off the radar for a while. I suddenly had to focus on some server issues #startuplife... I see though that the ball is rolling with help from @mappum - it looks really good! :) Let me know if there is anything I can do

**Comment by jbenet** [comment]
Hey @watson no worries. actually, making https://github.com/ipfs/node-ipfsd-ctl would be very helpful-- i had to ctx switch away from it. (I'll get it done sometime this week unless someone beats me to it)

**Comment by BillDStrong** [comment]
So, I remember reading about utorrent in the browser, and the fact that the browser doesn't support udp or tcp directly. What are you planning to use instead? Does your current protocol work over WebRTC? or would adopting some of the https://github.com/feross/webtorrent js code be a good starting point? 

They can't interface with current bittorent clients due to the limitations of the browser, so they are creating a dual node/iojs server that speaks both protocols as a stop gap, and they hope that other clients catch up.

If that will be an issue here, it might be something to look into doing, creating a web focused version over WebRTC.

**Comment by RichardLitt** [comment]
Closing. Refer to github.com/ipfs/js-ipfs for our current work doing this in JS.
