### ISSUE TITLE
What's the difference between `/ipfs/hash` and `hash`?

### ISSUE THREAD

**Issue by ysmood** [ipfs/ipfs#303]
What's the difference between

```
ipfs cat /ipfs/hash/readme
```

and

```
ipfs cat hash/readme
```
?

Why do we need the `/ipfs/` prefix?

**Comment by Stebalien** [comment]
Great question. I'd be more than happy to answer it on the support forum: https://discuss.ipfs.io/ :slightly_smiling_face:.

(we've discovered that issue trackers really don't make for good support forums)
