### ISSUE TITLE
How to debug stalls in hash resolution

### ISSUE THREAD

**Issue by masaeedu** [ipfs/ipfs#305]
I'm trying out ipfs, and am having some issues with the following basic experiment:

- Start the IPFS daemon in a container: `docker run -it --rm ipfs/go-ipfs`
- Start the IPFS daemon locally: `ipfs daemon`
- Create and add a file in the container: `echo "some content ..." > ./test && ipfs add ./test`. Record the hash
- Unpin and delete the file inside the container: `ipfs pin rm <the hash> && ipfs repo gc`. Confirm the gc shows the hash being deleted.
- Attempt to cat the file locally: `ipfs cat <the hash>`. This hangs, as expected; I assume it's looking far and wide across the DHT for this key. Confirm that `ipfs bitswap wantlist` shows the hash.
- Add the file again inside the container: `ipfs add ./test`

At this point, it seems to be a crapshoot whether the `ipfs cat` will actually resolve. I've waited sometimes for several minutes with nothing happening (I eventually canceled), and on other occasions seen the output immediately after `ipfs add` completes inside the container.

I'm assuming the difference each time I run the experiment is that there is a different path through the P2P network between me and the container (when things are very fast the container and I are probably direct peers).

My question is whether there is whether anything is actually changing in the network that ensures forward progress in resolving the hash, and is there any way I as a user can observe this? If not, and the expected behavior is just that you sometimes have bad luck and end up isolated from your target, should I deliberately try to add randomness (e.g. by cycling my peers) when I am unable to resolve it after a timeout?

**Comment by Stebalien** [comment]
```
PLEASE READ THE FOLLOWING BEFORE CREATING AN ISSUE

This repo exists just to provide an overview of the entire ipfs project and
ecosystem.  If you are about to file an issue about a certain implementation of
ipfs (for example, go-ipfs) Please instead file it in the appropriate location:

For actionable issues pertaining to BUGS in GO-IPFS, create an issue over at:
https://github.com/ipfs/go-ipfs/issues

For QUESTIONS and SUPPORT issues, go to:
https://discuss.ipfs.io

For anything else, please take a look at the project directory on this repos
README.md to find the appropriate location for your issue.
```

**Comment by masaeedu** [comment]
@Stebalien I did read that note, and this is a question about the IPFS protocol in general, not about any particular implementation of a client. When connecting to the network, how can a user track progress in finding the location of a hash (if this kind of progress is guaranteed), and if not, should they manually try to cycle their peers.

**Comment by Stebalien** [comment]
```
For QUESTIONS and SUPPORT issues, go to:
https://discuss.ipfs.io
```
