### ISSUE TITLE
I am working on Korean version of readme.md

### ISSUE THREAD

**Issue by harrythedev** [ipfs/ipfs#306]
Can we add a section for international language in readme.md for other translations?

**Comment by haoliangyu** [comment]
I also like this i18n idea. Maybe it is nice to have a checklist for the translation in progress. I can volunteer Chinese if needed.

**Comment by Mr0grog** [comment]
Is there a general plan for where translated docs should live? Since there are so many IPFS-related repos, we should figure out some structure that we can probably use in each.

I know https://crowdin.com is the service Electron uses for organizing their docs (they used to just manage it all manually), but I’m not especially familiar with how it works and whether it would apply well here.

**Comment by harrythedev** [comment]
@Mr0grog maybe a directory called `international version` in ipfs/ipfs or ipfs/community for readme?
i almost finished translating main repo's README.md and trying to get ipfs/js-ipfs README.md done next.

**Comment by shaharyar-shamshi** [comment]
I can contribute in Hindi language

**Comment by Gigi33** [comment]
I can contribute to German translations if these i18n efforts get some traction.

**Comment by harrythedev** [comment]
https://github.com/flyingzumwalt/decentralized-web-primer
this gitbook is going to replace official https://ipfs.io/docs/examples/ once it's finished.
I think it would be better to work on i18n version of those.
I'll ask @jbenet for his opinion on twitter.
Stay tuned!

**Comment by baolianbao** [comment]
I can contribute to Chinese translations

**Comment by Monotox** [comment]
I can contribute to Portuguese translations. It is very important to share the project with all the world.

**Comment by momack2** [comment]
Love the enthusiasm on this! I think a “translations” folder which is linked from the top of the readme for alternate language versions would be really useful.  @lidel - do you have any ideas or best practices from the translations project?

**Comment by lidel** [comment]
To contribute translation of `README.md`, just open a PR with translation  added as  `translations/<lang>/README.md` (to keep things tidy) and link  to it from the english original. A good example [here](https://user-images.githubusercontent.com/157609/57989385-3f79a600-7a9a-11e9-948a-a405b5bb7afb.png).

While we are at this, make sure to check [IPFS Translation Project  🌐✍️🖖](https://github.com/ipfs/i18n)
To start, go to https://www.transifex.com/ipfs/public/, login with github account, select languages you want to help with and start translating!
