### ISSUE TITLE
cant find resources on other peers

### ISSUE THREAD

**Issue by kiahmed** [ipfs/ipfs#309]
I have it running locally and web ui works file to browse the node info and peers but when try to search by a hash of a peerid or file , it can't find anything and in the console constantly get this error. I just change the swarp port to 4003, as I already have an openbazaar node running on default swarm port 4001..any idea?

[0;37m15:43:48.599 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m15:45:28.578 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m15:45:28.597 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m15:45:28.597 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m15:46:59.213 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m15:49:46.117 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m15:49:46.274 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m15:50:47.169 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m15:52:53.145 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m15:58:12.083 [31mERROR [0;34m   bitswap: [0mcouldnt open sender again after SendMsg(<peer.ID WMsDhC>) failed: dial attempt failed: misdial to <peer.ID WMsDhC> through /ip4/127.0.0.1/tcp/4001 (got <peer.ID QfbCEU>): read tcp4 127.0.0.1:23812->127.0.0.1:4001: use of closed network connection [0;37mwantmanager.go:237[0m
[0;37m16:00:11.144 [31mERROR [0;34m   bitswap: [0mcouldnt open sender again after SendMsg(<peer.ID cCPpTa>) failed: dial attempt failed: <peer.ID TaS5nK> --> <peer.ID cCPpTa> dial attempt failed: dial tcp4 138.197.98.10:4001: connectex: No connection could be made because the target machine actively refused it. [0;37mwantmanager.go:237[0m
[0;37m16:09:23.089 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m16:10:23.938 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m16:25:50.091 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m16:25:50.313 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m16:25:50.313 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m16:27:26.393 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m16:27:26.630 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m16:27:26.722 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m16:27:26.801 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m16:27:26.803 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m16:27:26.811 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m
[0;37m16:27:26.811 [31mERROR [0;34m   bitswap: [0mError writing block to datastore: Access is denied. [0;37mbitswap.go:317[0m

**Comment by Stebalien** [comment]
It looks like you might be experiencing: https://github.com/ipfs/go-ipfs/issues/3971.

I'm going to close this issue as it's off-topic for this issue tracker. In the future, if you're looking for support, try discuss.ipfs.io; if you're looking to report a bug in go-ipfs, report it at https://github.com/ipfs/go-ipfs.

**Comment by kiahmed** [comment]
not sure why this issue dont belong here? The other issue you pointed to , its partially related to this issue and already solved it with admin rights, but still ipfs dont find and object with hash that exists in the network

**Comment by Stebalien** [comment]
> not sure why this issue dont belong here? 

You should have seen the following notice when creating this issue:

```
PLEASE READ THE FOLLOWING BEFORE CREATING AN ISSUE

This repo exists just to provide an overview of the entire ipfs project and
ecosystem.  If you are about to file an issue about a certain implementation of
ipfs (for example, go-ipfs) Please instead file it in the appropriate location:

For actionable issues pertaining to BUGS in GO-IPFS, create an issue over at:
https://github.com/ipfs/go-ipfs/issues

For QUESTIONS and SUPPORT issues, go to:
https://discuss.ipfs.io

For anything else, please take a look at the project directory on this repos
README.md to find the appropriate location for your issue.
```
