### ISSUE TITLE
ipfs add file doesn't seem to propagate 

### ISSUE THREAD

**Issue by Grobeu** [ipfs/ipfs#311]
So I installed IPFS and added a file. I tried to open it with the public gateway of IPFS but it doesn't load anything, and hangs up on load. I tried to cat it using js-ipfs but it still doesn't work. (opening the cat.jpg work though)

Should I keep the node I added the file with for some time, for it to be propagated? 

I'm unsure about the working of js-ipfs, but if it connects directly to the IPFS swarm, normally it should get the file from the node I uploaded the file with, no?

Help will be appreciated

**Comment by Stebalien** [comment]
We've switched to [https://discuss.ipfs.io](discuss.ipfs.io) for support. Please ask any support related questions there.
