### ISSUE TITLE
What if someone deletes my blocks folder from .ipfs folder?

### ISSUE THREAD

**Issue by prakharrke** [ipfs/ipfs#321]
What if someone deletes my blocks folder or datastore folder from my .ipfs folder? What would happen to the data that I have added to ipfs?
Would it be removed? If so, is that not a problem while using IPFS to store sensitive data and completely relying on my machine to host that data?

**Comment by Stebalien** [comment]
While a real issue, this problem really related to ipfs; if you delete your files, you'll lose your files. If you want replication, I recommend either backing your `.ipfs` folder or, if the files aren't sensitive, using an ipfs pinning service to replicate them.
