### ISSUE TITLE
Cryptography & Anonymity thread [again]

### ISSUE THREAD

**Issue by Illasera** [ipfs/ipfs#329]
With the upcoming EU article 13 copyright issue and let's face facts, each year there is a new threat.

A PR opportunity presents itself with restructuring the web with IPFS + blockchain as URN/IPFS path book-keeper.

**Suggestion** :  adding ring signature to IPFS core, Yes , I know, it means re-writing half of IPFS protocol including the DHT (Can it even work with DHT without a conflict? I need to do some research);

There are also endless reasons to why its not practical, But we MUST talk about it , Otherwise IPFS can be used by ISPs as a major tracker to everyone who owns a copy of a stream that one shouldn't have (as dictated by the public sector) (This is part of how ISPs detected torrent users).

If we wish for IPFS to take off, Anonymity is a MAJOR seller.

**Comment by Stebalien** [comment]
So, a ring signature is a specific cryptographic primitive. "Adding ring signatures to IPFS core" is kind of like saying "adding aluminum to a building".

Now, censorship resistance *is* something we need to discuss. However, we have a bunch of open issues for that here: https://github.com/ipfs/notes/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+censorship

If you have any specific ideas, feel free to open an issue in [ipfs/notes](https://github.com/ipfs/notes).

**Comment by Stebalien** [comment]
However, thank you for continuing to bring this up. It *is* a very important topic that needs to be discussed. I just don't want to further fragment the existing discussion.
