### ISSUE TITLE
IPFS is a promising project.

### ISSUE THREAD

**Issue by gantleman** [ipfs/ipfs#339]
IPFS is a promising project.
But before we recall how bit spirit failed.
The failure of bit spirit is that the download speed can not meet the demand.
Download speed is slow because public network nodes and bandwidth are too few.
Because people who upload documents do not get the rewards they deserve.
It includes bandwidth and file storage space.
But I think providing uploading is the key to reward.
That is to say, those who provide bandwidth should receive generous rewards.
His reward comes from the man who gets the document.
The characteristic of P2P download is that the download channel comes from a scattered tree structure.
How to assign rewards to tree structures is a big problem.
I don't think P2P must be associated with mining.
He should combine directly with the mature currency system such as bitcoin, ether currency and so on.
Money is used to reward the downloader.
The person who downloads the file has to pay for the downloader.
Establishing such a payment system is the most promising thing for IPFS.

For example, the following scenario:
I want to download a file.
And created a token to store 0.1 eth. in this token.
And create 20 sha256 encrypted random numbers.
Anyone who gave me one of the documents 1/20.
I'll give him the original sha256.
He can go to token and get the reward with the original.
Until all the documents have been completed.

**Comment by bleonard252** [comment]
Umm I'd like to not have to pay to use IPFS.

**Comment by gantleman** [comment]
> Umm I'd like to not have to pay to use IPFS.

@bleonard252  no pay no market economy no current world. all IPFS to Communism？

**Comment by momack2** [comment]
Hey - sounds like you'd like the incentivized file storage marketplace designed specifically to go with IPFS - check out [Filecoin](https://filecoin.io/), specifically the retrieval marketplace.
