### ISSUE TITLE
Develop live stream application based on IPFS

### ISSUE THREAD

**Issue by Juelun** [ipfs/ipfs#344]
Is there anyone develop live stream application based on IPFS? Is there an open source project exist already?

**Comment by lgierth** [comment]
Yes here: https://github.com/tomeshnet/ipfs-live-streaming

**Comment by diasdavid** [comment]
@benhylau where can people find more information about the IPFS Live Streaming?

**Comment by lgierth** [comment]
Meant to post this video from Our Networks: https://ipfs.io/ipfs/QmbqonFZFJoF9d44TQx7AxN521iwnGzTyRMudfRMxSzbhu (removed my previous comment)

**Comment by daviddias** [comment]
@Juelun You can also find the presentation describing the whole project at https://ipfs.infura.io/ipfs/QmWsKvBvXUKaHcHzrUS91XV4k3YjQFdywQ7bY9BZVX4ghk

For the future, http://discuss.ipfs.io/ is a better platform to ask these questions. Thanks!
