### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by ayushkaul95** [ipfs/ipfs#345]
I wanted to store user data on IPFS which is dynamically increasing. Is there any constrain on the total size of data stored by a single peer node on global IPFS network ?

**Comment by ayushkaul95** [comment]
okay. But can you let me know the mechanism behind this (any source you know).

**Comment by stasbar** [comment]
You can compare IPFS to Torrent network, why would there be any size limit ?

**Comment by magik6k** [comment]
When you add something with `ipfs add`, the data gets stored in datastore which by default is in `~/.ipfs`. Blocks aren't replicated by other peers automatically, so the only constrain is your node capacity.

**Comment by Stebalien** [comment]
Please try to direct questions to discuss.ipfs.io. You may also be interested in https://discuss.ipfs.io/t/question-about-content-distribution-in-ipfs/3235
