### ISSUE TITLE
.m4a delivered as application/octet-stream

### ISSUE THREAD

**Issue by Hazae41** [ipfs/ipfs#348]
When a .m4a file is delivered by ipfs.io or any gateway, it's response header has "content-type: application/octet-stream" while it should be "audio/..."

**Comment by lidel** [comment]
I don't think this should go into go-ipfs repo.

Please close this issue and open a new one in https://github.com/ipfs/go-ipfs.
Remember to include example of CID or URL to public gateway that demonstrates the issue.

Thanks!

**Comment by Stebalien** [comment]
See: https://github.com/ipfs/go-ipfs/issues/2164
