### ISSUE TITLE
i want to join python-ipfs implant

### ISSUE THREAD

**Issue by CodeMan-lol** [ipfs/ipfs#356]
i want to join to dev python-ipfs.  i saw this project starting.   i am a python developer.  i work for eos blockchain.   i am interested in blockchain and ipfs.   i used python,golang,php.  ipfs is cool.  so i want to join it and dev a new internet.   
so how can i join python-ipfs.   first maybe i can pr, but there are maybe other developer  build it.  so i create this issue.  i hope to join them,but i don’t how to do that.
and sorry to create this issue just to do for that.  but i’m really interested in ipfs.   

if you have free time, please give a replay.  and if i can’t join it,please give me some advice to tell me how to contribute.

thanks,
goooo

**Comment by daviddias** [comment]
Hi @CodeMan-lol! We want it too :)

Check https://github.com/ipfs/py-ipfs and https://github.com/ipfs/py-ipfs/issues/1 for the beginnings of it. Fortunately, there is already a py-libp2p -- https://github.com/zixuanzh/py-libp2p/ -- implementation in the works that builds most of what the IPFS protocol internals are.

Check those links out and let's continue the convo there :)

**Comment by alexander255** [comment]
BTW: Regarding `py-ipfs` there is also issue https://github.com/ipfs/py-ipfs/issues/49 which lists the current “next steps” tasks to get py-ipfs off the ground. (Please also link to that in the future rather than the overcrowded issue 1.)
