### ISSUE TITLE
"Translation Project" link not working

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/ipfs#357]
Currently, the link "translation project - Crowdsourced translation of IPFS WebUI and the ipfs.io website." in the readme leads to a 404.

Link goes to https://www.transifex.com/ipfs/ipfs/

cc @lidel

**Comment by lidel** [comment]
Good catch! Proposed a fix in  https://github.com/ipfs/ipfs/pull/358

**Comment by VictorBjelkholm** [comment]
Thanks! :)
