### ISSUE TITLE
Cloudflare's move should be deeply concerning to you

### ISSUE THREAD

**Issue by kareldonk** [ipfs/ipfs#362]
After all the control, censorship, privacy violations and general abuse and disrespect that companies such as Apple, Google, Facebook, Twitter and others have demonstrated recently, the trend is now that developers are looking more and more at creating distributed and decentralized alternatives to the existing centralized services on the Internet. It looks like Cloudflare wants to position itself as much as possible as some kind of gatekeeper in order to be able to control those alternatives, much like Google and Facebook on today’s Internet.

https://medium.com/@kareldonk/i-dont-trust-cloudflare-with-ipfs-fce6786af658

**Comment by Stebalien** [comment]
Please move this discussion to https://discuss.ipfs.io. It's an important discussion to have but really doesn't belong in *this* repo .
