### ISSUE TITLE
General comments

### ISSUE THREAD

**Issue by ShenJunNeo** [ipfs/ipfs#366]
IPFS is target to a new WEB world. But why you are still only using traditional HTTP Webs. Could you please maintain a IPFS based Web for current ipfs.io and filecoin.io ?

**Comment by lidel** [comment]
FYI both mentioned websites have [DNSLink](https://docs.ipfs.io/guides/concepts/dnslink/) set up and can be loaded from IPFS: 
[`/ipns/ipfs.io`](https://ipfs.io/ipns/ipfs.io/), [`/ipns/filecoin.io`](https://ipfs.io/ipns/filecoin.io/)

If you had something else in mind, please provide more details.
