### ISSUE TITLE
checksum mismatch

### ISSUE THREAD

**Issue by UltraNote** [ipfs/ipfs#367]
Hi,
For some time now we are getting a load of errors. I hope you can help us find what causing it. We are running last ipfs version.
![screenshot from 2018-10-16 08-34-30](https://user-images.githubusercontent.com/31513990/46997062-000f6380-d11f-11e8-8a69-a8877f9b672b.png)

Another error for ipns 
![screenshot from 2018-10-16 08-42-38](https://user-images.githubusercontent.com/31513990/46997420-ef132200-d11f-11e8-9b6d-45ea6ada702c.png)

Kind Regards
UltraNote Team

**Comment by Stebalien** [comment]
Please try building go-ipfs from master, this looks like: https://github.com/ipfs/go-ipfs/issues/4981. You can also try using https://github.com/ipfs/go-ipfs/issues/5402#issuecomment-416327668 to manually fix your datastore.

FYI: In the future, this is a go-ipfs bug and should be reported at https://github.com/ipfs/go-ipfs/issues

(closing for tracking purposes, feel free to ask followup questions)

**Comment by UltraNote** [comment]
Will do, Thank you for your help.
