### ISSUE TITLE
Support for Ipfs on mobile devices

### ISSUE THREAD

**Issue by vasa-develop** [ipfs/ipfs#376]
I want to know about

a) What is the current stage of support for Ipfs on mobile devices? Is it supported for both Android and Apple right now(P.S. I have checked out https://github.com/ligi/IPFSDroid)?

b) How feasible is to run an Ipfs node on a mobile device? Does it drains the battery too much when the node is run for a long time?

c) What is the priority of supporting Ipfs on mobile devices with respect to development on a scale from 1-10?

**Comment by DougAnderson444** [comment]
There is a note open for mobile already here
[https://github.com/ipfs/notes/issues/68]
