### ISSUE TITLE
about file stores

### ISSUE THREAD

**Issue by StupidStudentInSchool** [ipfs/ipfs#379]
As far as I know, a file is split into multiple paths, each of which stores 262144. If the storage address is damaged, is the file damaged?

**Comment by Stebalien** [comment]
> As far as I know, a file is split into multiple paths, each of which stores 262144.

With the *default* datastore, correct.

> If the storage address is damaged, is the file damaged?

Yes. At a slight performance cost, you can configure IPFS to check chunk hashes when it reads them (`ipfs config --json Datastore.HashOnRead true`) however, that won't *repair* damaged files. You can also verify the entire repo by running `ipfs repo verify`.
