### ISSUE TITLE
Ipfs hash can replaced by file name

### ISSUE THREAD

**Issue by chawla007** [ipfs/ipfs#389]
I am having a problem using ipfs
1. I want to change the name of multihash of the file to the original name of my file. Is it Possible that i can replace that hash to my filename.
2. The file which i have uploaded is in what format how can i know?

I have multiple application jars which i want to upload to the ipfs and i have a requirement in which i want to get the file in the same format and same name.

**Comment by Stebalien** [comment]
> For QUESTIONS and SUPPORT issues, go to:
https://discuss.ipfs.io
