### ISSUE TITLE
ipfs 0.4.18 reproducebly crashes

### ISSUE THREAD

**Issue by skliarie** [ipfs/ipfs#391]
ipfs 0.4.18 reproducebly crashes, when I do ipfs add this IPNS: /ipns/QmdwSsWWao7qK1ceVxgis6z8U7TsPsUUk3HxRPVKr3DvSh 

Attaching crashdump log:

[ipfs_0.4.18_crashdump.txt.gz](https://github.com/ipfs/ipfs/files/2850276/ipfs_0.4.18_crashdump.txt.gz)

**Comment by Kubuxu** [comment]
This isn't the right place for this issue, please report it to https://github.com/ipfs/go-ipfs
