### ISSUE TITLE
IPFS/Angular/Hyperledger Composer Question

### ISSUE THREAD

**Issue by kwakwaa** [ipfs/ipfs#392]
Hello,

I've been working on creating a decentralized app recently and lately I've been trying to solve the issue of storing bigger files and came to the conclusion that it would be wiser to use IPFS to store these files and simply store the file hash on the blockchain itself but no matter how much I try I can't seem to get it to work...

Taking into consideration that I am using hyperledger composer which forced me to use previous versions of Node and npm (v8.11.4 and v5.6.0 respectively) coupled with the fact that my app is built on Angular I can't seem to get this working, so far I've only found one guide on this particular subject (angular+ipfs) which is [here](https://medium.com/@GrandSchtroumpf/ipfs-and-angular-6-6165e6fd6e5d), and I'm guessing from using previous releases of node and npm I keep getting errors whenever I try to implement that... 

So my question is, is what I'm doing even possible ? Because i'm starting to question that, I have no idea where to start and all i'm looking for is a way to store and access files through Angular using previous releases of Node and npm and i'm not really getting anywhere...

Thank you so much for taking the time to read this and for your help!

**Comment by Kubuxu** [comment]
This would be a great question to post on https://discuss.ipfs.io , you have a higher chance of finding an answer there.

**Comment by vmx** [comment]
https://discuss.ipfs.io/t/ipfs-angular-hyperledger-composer-issue/4856
