### ISSUE TITLE
IPFSObject lacks metadata

### ISSUE THREAD

**Issue by jalmasi** [ipfs/ipfs#397]
Just read the white paper, this is the basic object:

type IPFSObject struct {
  links []IPFSLink
  // array of links
  data []byte
  // opaque content data
}

Although IPFS doesn't need anything else, applications do need metadata, and I think that IPFS should store it. This might just be the right place to do so.
Metadata, like, MIME type. It is usually inferred from filename extension, but it may not work well every time; for example, file with .3gp extension may be of video/3gpp or audio/3gpp multimedia type.
Or, text file encoding.
And so on.
A web site may decide on proper MIME, encoding and other metadata because it serves it's own content. But that's just not the case with content that's distributed globally.
Rather than introducing specific structure(s) and enforcing them, maybe just leave metadata structure(s) to applications, and just store them. I.e. metadata []string just might do, just like mail message stores headers, but maybe metadata map[string]byte would be better.

**Comment by Stebalien** [comment]
So, that's the "merkledag" datastructure we use to encode the _graph_. We store the actual file data in a second protobuf, embedded in the data section of that protobuf.

That is, we:

1. Create a unixfs protobuf (https://github.com/ipfs/go-unixfs/blob/master/pb/unixfs.proto).
2. Serialize this.
3. Stick it in the data field of the `IPFSObject` (well, we now call it `DagPB`) protobuf.
4. Serialize _that_.

---

Note: We're (slowly) working on a V2 format that uses CBOR objects at the core (https://github.com/ipfs/unixfs-v2). This should make it easier to extend the protocol and add arbitrary metadata, file types, etc.
