### ISSUE TITLE
Received interrupt signal, shutting down...

### ISSUE THREAD

**Issue by dominic-healid** [ipfs/ipfs#399]
The daemon just stops after a few hours inactivity, it doesn't give any error message just the `Received interrupt signal, shutting down...`

Is there someone that can point me to a possible cause of this issue?

Thanks

**Comment by Stebalien** [comment]
That usually means either:

1. Something sent the interrupt signal (control-C, SIGINT, etc.) to the daemon.
2. Something called `ipfs shutdown`.

How are you running the daemon and what version are you using?

**Comment by dominic-healid** [comment]
@Stebalien thanks for the response.

This is the command i used to run daemon: `ipfs daemon >> ipfs.log 2>&1 &`

**Comment by dominic-healid** [comment]
could it be possible that it shutdown the moment my terminal command disconnected on the server? However the daemon is running on the background

**Comment by Stebalien** [comment]
> could it be possible that it shutdown the moment my terminal command disconnected on the server? However the daemon is running on the background

That's exactly it. The terminal will send a SIGHUP when it exits. Try using `nohup ipfs daemon &`.

**Comment by dominic-healid** [comment]
Wow thanks for the info will try that out. :)

**Comment by dominic-healid** [comment]
Hi @Stebalien, regarding this issue I thought it is already fixed but unfortunately it didn't. It looks like it still terminate daemon whenever my terminal disconnects on the server. I have already added `nohup` but it doesn't seem to fix the issue.

**Comment by Stebalien** [comment]
Does your server kill _other_ programs as well? Are you using systemd? If so, is `KillUserProcesses` (in /etc/systemd/logind.conf) set to `yes`?

**Comment by peterQiu** [comment]
I have also encountered the same problem.
log like this:
Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)
Initializing daemon...
go-ipfs version: 0.4.19-
Repo version: 7
I run ipfs with command: nohup ipfs daemon &, but it still shutdown over time,strange.
