### ISSUE TITLE
why gateway timeout constantly?

### ISSUE THREAD

**Issue by hoogw** [ipfs/ipfs#403]
try this, choose any gateway, then click the cube icon.

[https://transparentgov.net/json2tree/ipfs/ipfsList.html](https://transparentgov.net/json2tree/ipfs/ipfsList.html)

Browser without ipfs extention. ( with chrome ipfs plug-in, performance will be normal) 
Most of gateway will timeout.  
All those pdf file hosted on 3 machine. 
1 pc (dynamic IP, 192.168.1.xx)
2 mac(static IP 75.18.212.228, 229)

Why timeout? why slow?
What if I setup my public gateway on my server, and use my public gateway would speed up? or Quick response the file?

**Comment by Stebalien** [comment]
I've created an issue (https://github.com/ipfs/go-ipfs/issues/6383) to track this and explain common problems.
