### ISSUE TITLE
i have upload image of IPFS using nodejs, uploading two images on same time but same hash generate all time. what is the issue?

### ISSUE THREAD

**Issue by RahulQuest** [ipfs/ipfs#405]
generating same ipfs hash alltime
<pre>
 if (result == '') {
   
                  horseImage.mv('assets/images/horse-image/'+horse_image, function(err) {
                    if (err)
                      return res.status(500).send(err);
                  });

                  
                  ped_Image.mv('assets/images/pedigree-image/'+pedigree_image, function(err) {
                    if (err)
                      return res.status(500).send(err);

                  
                  });

  
                let horseFile = fs.readFileSync("C:/Users/Priyaka/Desktop/latest_horce_chain/assets/q2.jpg");      
               
                let horseBuffer = new Buffer.from(horseFile);
                  ipfs.files.add(horseBuffer, function (err, file) {
                    if (err) {
                      console.log(err);
                    }                
             
                let ipfs_hash =file[0].hash;
                console.log('ipfs_hash');
                console.log(ipfs_hash);

                let pedigreeFile = fs.readFileSync("C:/Users/Priyaka/Desktop/latest_horce_chain/assets/q1.jpg"); 

               let PedBuffer = new Buffer.from(pedigreeFile);
                  ipfs.files.add(PedBuffer, function (err, files) {
                    if (err) {
                      console.log(err);
                    }
             
               
                let ipfs_hash_ped_img =files[0].hash;
                console.log(ipfs_hash_ped_img);
              });
              });
             }
</pre>

**Comment by hoogw** [comment]
same hash = same image 
check your image, make sure they are not same

**Comment by RahulQuest** [comment]
but i am using different image

>

**Comment by Stebalien** [comment]
Please ask support questions on [discuss.ipfs.io](https://discuss.ipfs.io).
