### ISSUE TITLE
What are the differences between IPSOU, LibP2P, and Multiformats?

### ISSUE THREAD

**Issue by apandacomefromchina** [ipfs/ipfs#408]
I know that there are already many projects based on IPFS, like IPSOU, LibP2P, Multiformats. But I want to know what is the difference between them.

**Comment by coderinAU** [comment]
IPSOU is a program come from China,
Libp2p come from Protocol Laboratory.

**Comment by Stebalien** [comment]
* IPSOU is a search engine for IPFS.
* IPFS is a decentralized content distribution system.
* Libp2p is a peer-to-peer networking library, used by IPFS.
* Multiformats is a set of format/specs for "self describing" data. That is, data that includes additional information about its type.

Closing for tracking as this isn't really the right place to ask questions. If you'd like to continue this discussion, please head over to https://discuss.ipfs.io.
