### ISSUE TITLE
[Feature] Add i2p Support

### ISSUE THREAD

**Issue by ghbjklhv** [ipfs/ipfs#409]
**Feature**: Add i2p support
**Why?**: Privacy and security are important issues. IP anonymity is at its forefront. 
**How?**: BitTorrent already has wide usage of i2p thank to i2p-snarks and [XD](https://xd-torrent.github.io/).

- [ ] Add Proxy Support
- [ ] Add .i2p [Bootstrap Node](https://docs.ipfs.io/guides/examples/bootstrap/)
- [ ] Add i2p Peers
- [ ] Add i2p Support to js-ipfs, go-ipfs, and ipfs-desktop Implementations
- [ ] Add i2p Only Toggle/Support to go-ipfs and ipfs-desktop applications.
- [ ] Complete i2p Support 

___________________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75249500-feature-add-i2p-support)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/BountySource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=75249500)](https://www.bountysource.com/issues/75249500-feature-add-i2p-support)

**Comment by daviddias** [comment]
duplicate of https://github.com/ipfs/notes/issues/380

**Comment by marek22k** [comment]
> duplicate of [ipfs/notes#380](https://github.com/ipfs/notes/issues/380)

The repo has been archived in the meantime. Maybe it makes sense to reopen this issue then?!
