### ISSUE TITLE
Search and announce source in DHT by hash prefix.

### ISSUE THREAD

**Issue by ivan386** [ipfs/ipfs#412]
Nodes that have many blocks in repo [may have hashes that have same 3 bytes and more prefix](https://en.m.wikipedia.org/wiki/Birthday_problem) (begin). They can publish all that blocks at ones by hash prefix. Later after others they can publish each hash individually.
      Other node can try 3 bytes and more prefix to find content.
      Cid allow to use only prefix:
  ```
  ipfs cid format -f%P F01551203AABBCC
  cidv1-raw-sha2-256-3
  ```

**Comment by Stebalien** [comment]
Even with the birthday paradox, there's a trade-off here that makes problematic in practice:

* For this to be useful to a node publishing, the prefix has to be small enough to have collisions (shared bytes) on that node.
* For this to be useful to the network, the prefix needs to be large enough to have few collisions on the entire network.

Unfortunately, the number of collisions scales with the amount of content and network will have orders of magnitude more content than an individual node.

---

However, one thing we _can_ do is batch content routing puts. That is, we can add a `PutMany` method to the DHT that takes all inputs, hashes them, sorts them and then puts nearby records as batches.

**Comment by hsanjuan** [comment]
I'm going to close this old issue but would like to point any future discussion to https://github.com/libp2p/notes/blob/master/OPEN_PROBLEMS/ROUTING_AT_SCALE.md (context) and https://discuss.libp2p.io (libp2p discussion forums). Thanks!
