### ISSUE TITLE
how to customize file name  by /api/v0/get

### ISSUE THREAD

**Issue by hoogw** [ipfs/ipfs#417]
/api/v0/get

I try to get downloaded file as xxx.zip, 

add &output=xxx.zip does not work.  the file name is always "get" 
                                http://localhost:5001/api/v0/get?arg=QmVjMzmryeWLfmxHo3GEY8iiCK6A69ertoiSZShoTqqTCF&output=xxx.zip&archive=false

also those does not work. 
                      &compress=false
                      &archive=false

how to download a file as   " .zip" ?
how to download a file not zipped?

**Comment by Clay-Ferguson** [comment]
I'm just getting started with IPFS but i have a bit of code that might help here:

https://github.com/Clay-Ferguson/SubNode.org/blob/master/src/main/java/org/subnode/service/IPFSService.java

the 'objectCat' can get data. The 'get' and MerkleNode stuff in there is how you can get kind of 'metadata' about things like zip files.  But also you can get/post arbitrary data, so if you want to post some zipped content just Zip the stream before sending it to IPFS.

For example, if you are using Java I'm sure searching for "zip" in my codebase will turn up some examples of how to zip.

**Comment by Stebalien** [comment]
We'd be happy to answer on the discussion forums, https://discuss.ipfs.io.
