### ISSUE TITLE
How to Get the file format type

### ISSUE THREAD

**Issue by mydoto** [ipfs/ipfs#420]
When I get file from IPFS via Qm... hash, i download a file with no format type.  
So I can not use the file derectly.

For example, when i get a .mp3 file from IPFS，i will download a file named Qm......，no type，i can not open it.    

will improve it ?

**Comment by Clay-Ferguson** [comment]
I was very confused by this also, until I realized it works just like an "HTTP get" does. The contentType will be in the HEADER, just like in an HTTP get of an image or other binary data, even though the content type is not built into the IPFS protocol in any really good way (IMO).

**Comment by Stebalien** [comment]
You can add files with `ipfs add -w` to "wrap" them in a directory. This will preserve the filename.

There are also plans to record metadata like mime types along with files but, unfortunately, progress has gotten a bit stuck on this front.

**Comment by Stebalien** [comment]
(closing as questions/discussions like this really belong on discuss.ipfs.io).
