### ISSUE TITLE
ipfs can not discovery automatic

### ISSUE THREAD

**Issue by shenxiaofeng1** [ipfs/ipfs#423]
In a private network，I have three nodes.A、B、C。
run>> ipfs swarm addrs ,
QmT6i9hdQj5Dm9JVVkFyhGKhFietRyhyShUdpg7t68pPUK (1)
	/ip4/127.0.0.1/tcp/4001
QmX3e8eVyD3PDeLw94QHvMPfVPxD98Ypi3xRFm2Pc5g4rC (1)
	/ip4/127.0.0.1/tcp/4001
But when i run >>ipfs swarm peers,i can't see nothing! It's empty

**Comment by shenxiaofeng1** [comment]
I know ,node A have finded node B and C. Why they can't connect each other?

**Comment by Stebalien** [comment]
Please ask support questions on the forums: https://discuss.ipfs.io.
