### ISSUE TITLE
ipfs publickey and privatekey

### ISSUE THREAD

**Issue by froud** [ipfs/ipfs#427]
Can I use ipfs' publickey and privatekey for asymmetric encryption?

**Comment by froud** [comment]
What is IPFS's privatekey format?  it starts with CAA(), unlike most keyPair that start with MII
forexample:
![image](https://user-images.githubusercontent.com/23519709/63152960-b1cd3880-c03f-11e9-9972-aa669c3ed869.png)
![image](https://user-images.githubusercontent.com/23519709/63152980-bc87cd80-c03f-11e9-82fc-c54cbeadf2f6.png)

**Comment by froud** [comment]
what should i do if i want to user the ipfs's publickey to encryption the file and decrypt the file by  ipfs's  privatekey?  The most important question is that I can't convert the ipfs's  privatekey that starts with CAA to RSAPrivatekey object.

**Comment by Stebalien** [comment]
For QUESTIONS and SUPPORT issues, go to:
https://discuss.ipfs.io
