### ISSUE TITLE
Data storage security issues

### ISSUE THREAD

**Issue by zdYng** [ipfs/ipfs#440]
How to ensure data security and data perfection？？

**Comment by zdYng** [comment]
Whether to consider adding a data content encryption key

**Comment by zdYng** [comment]
Key management mechanism

**Comment by zdYng** [comment]
Whether data storage redundancy is considered to reduce deduplication nodes

**Comment by Stebalien** [comment]
This is a good question. Please ask on https://discuss.ipfs.io.
