### ISSUE TITLE
Work with existing organizations to improve adoption

### ISSUE THREAD

**Issue by tysonzero** [ipfs/ipfs#453]
It would be great to see IPFS used in more places and to be able to use it more in my own projects. Unfortunately it's often hard from a business perspective to make the full jump into IPFS.

For this reason I think the following approach could be taken to convince companies to adopt IPFS:

* Convince them to expose multihash links to their public content, such as `cas.example.com/QmXo...`.

* Convince them to upload this content automatically to IPFS

For example with GitHub:

I currently dislike directly referencing GitHub archives, as organization name changes, project name changes, and various deletions could all threaten the permanence of that link. I would much prefer referencing a hash instead, particularly if I could easily pin that content to guarantee it didn't get deleted.

The second step would then decentralize the serving of this content, to minimize chance of data loss and downtime. It would also allow organizations to seamlessly help host this content on IPFS without any URL changes. As well as all the various other advantages of IPFS.

This could apply to Amazon S3/CloudFront, to Hackage, to GitLab, to Google Hosted Libraries, and to many other organizations.

**Comment by tysonzero** [comment]
I've done my part on this front by creating feature request tickets with a few organizations. However I don't have much influence on this front by myself.

**Comment by hsanjuan** [comment]
We try our best to convince them, but this is a tough game that requires heavy investments from all sides (not just monetary, but also in terms of capacity, willingness and moral alignment).

In any case, this is a discussion for our forums rather than for this repo: https://discuss.ipfs.io . Thanks!
