### ISSUE TITLE
Reference and/or implement IPFS kernel modules

### ISSUE THREAD

**Issue by tmagik** [ipfs/ipfs#466]
So this was closed 6 years ago, with a comment about 
> and we'll eventually write our own kernel driver

Does such a thing yet exist, cause I'll use it.

Otherwise, if you know of a distributed filesystem that's had as much adoption and use as AFS, please let me know, as I'm about to go full-on in attempting to bring AFS into the decade where everyone has an IPv6 address, half the world has a linux based phone on their desk (thank you Google), and IPFS is the next "new big thing".

There are some really nice things about IPFS... It seems to me like a great way to package and distributed read-only AFS volumes that you want to share with the rest of the world (like say the Debian archive in AFS, or the gajillion NodeJS modules, or maybe the binaries and everything else for Golang or Rust)

But we still need a kernel module.

_Originally posted by @tmagik in https://github.com/ipfs/ipfs/issues/40#issuecomment-806315127_

**Comment by BigLep** [comment]
@tmagik and @jnorthrup : this repo isn't triaged for new issues.  For general IPFS discussions, please post in https://discuss.ipfs.io/ so other community remembers and maintainers have a higher chance of seeing and responding.  Thanks.
