### ISSUE TITLE
Cleanup "docs" around other implementations and the IPFS community

### ISSUE THREAD

**Issue by BigLep** [ipfs/ipfs#487]
As part of https://2022.ipfs-thing.io, we want to:
1. Drive home the message that IPFS is many implementations by multiple groups.  Basically IPFS is not go-ipfs or Protocol Labs.  https://github.com/ipfs/ipfs-docs/pull/1193
2. Provide accurate information about how to engage with the community.

Historically:
1. "ipfs" has been used to denote "go-ipfs" (Kubo), which is wrong since ipfs is bigger than a particular implementation.  
2. Community information has been spread across various GitHub repos.

We want to have canonical information about IPFS implementations and community information that other places can link to.  https://docs.ipfs.io is the intended place that we should link to.

This tracks the work to cleanup old/wrong areas about our "docs".  Example areas in scope:
- https://github.com/ipfs/ipfs
- https://github.com/ipfs/ipfs-docs
- https://github.com/ipfs/community
- https://github.com/ipfs/team-mgmt
- https://github.com/ipfs/roadmap
- https://github.com/ipfs/notes

There is a lot of stuff (including cruft) in these repos.  To maintain focus and contain the scope, this issue is focused on the two items above.

This issue is here so can link to it in various PRs to provide context.

- [x] https://github.com/ipfs/ipfs-docs/pull/1193
- [x] https://github.com/ipfs/ipfs-docs/pull/1195
- [x] https://github.com/ipfs/ipfs/pull/486
- [x] https://github.com/ipfs/ipfs-docs/issues/1194
- [x] https://github.com/ipfs/community/pull/760
- [x] https://github.com/ipfs/team-mgmt/pull/1204
- [x] https://github.com/ipfs/roadmap/pull/92
- [x] https://github.com/ipfs/js-ipfs/pull/4157
- [x] https://github.com/ipfs/js-ipfs/pull/4156
- [x] https://github.com/ipfs/js-ipfs/pull/4158
- [x] https://github.com/ipfs/js-ipfs/pull/4159
- [x] https://github.com/ipfs/js-ipfs/pull/4160

**Comment by tinytb** [comment]
It appears that this is blocked by https://github.com/ipfs/kubo/issues/9124 -- is that correct?

**Comment by BigLep** [comment]
I think this has been handled by this point with the various changes over the last 1.5 years.  I'm not aware of any major open items.  Resolving.
