### ISSUE TITLE
IPNS over DHT when querying website is quite slow

### ISSUE THREAD

**Issue by EthanScully** [ipfs/ipfs#492]
When only DHT IPNS name service is used on my personal gateway, it seems that every http request, even when milliseconds apart, need a separate IPNS name lookup. This can make a website with many images that load at once take a very long time. When IPNS over PubSub is enabled, this is eliminated to an unnoticeable level. 

Shouldn't the gateway assume the IPNS name reference is the same for a given amount of time instead of looking it up every single time.

Anyway, I'm using the latest docker image

**Comment by BigLep** [comment]
Please search/ask in https://discuss.ipfs.io/.
