### ISSUE TITLE
Can't upload 400+MB files

### ISSUE THREAD

**Issue by nabhan-rp** [ipfs/ipfs#500]
I can't upload directly use import folder funtion into ipfs using ipfs desktop windows.
This is look stucking in 0 import files, but if I import subfolder inside this, can be added.
![image](https://user-images.githubusercontent.com/78986005/211296671-b2ae8e32-288a-4839-a20c-1928785ce2af.png)

**Comment by 2color** [comment]
This isn't the repo for this. For help, use the IPFS Forums
