### ISSUE TITLE
Update ipfs demo readme to have proper sentence case

### ISSUE THREAD

**Issue by momack2** [ipfs/ipfs#67]
Update *ipfs cat /ipfs/Qmcqtw8FfrVSBaRmbWwHxt3AuySBhJLcvmFYi3Lbc4xnwj/readme* to "Use at your own discretion!"

Current text is:
"Warning:
|   This is alpha software. **use** at your own discretion! |
|   Much is missing or lacking polish. There are bugs.  |
|   Not yet secure. Read the security notes for more.  |"

**Comment by dylanPowers** [comment]
@jbenet Is there a repo somewhere with this content?

**Comment by whyrusleeping** [comment]
this text comes from go-ipfs/assets

**Comment by dylanPowers** [comment]
Thanks @whyrusleeping
