### ISSUE TITLE
Java/CPP-ipfs implementations?

### ISSUE THREAD

**Issue by PayasR** [ipfs/ipfs#71]
These conventional languages have a plethora of libraries available, and have a large programmer base. As go-ipfs reaches alpha, we can start with alternative implementations in other languages (similar to py-ipfs). Java/CPP are battle tested and can catch up quickly too.

**Comment by mseri** [comment]
Or Rust that is low-level and should provide memory safety

**Comment by PayasR** [comment]
https://godoc.org/golang.org/x/mobile/app
if go-ipfs can be ported to android and iOS, i guess we dont require the CPP version of it. I am not too sure though as I'm not familiar with golang.
@jbenet @whyrusleeping, can you please comment?

**Comment by whyrusleeping** [comment]
go-ipfs can be ported to android and iOS, but some work will need to be done on limiting resource consumption, and also making some sort of UI for the app.

**Comment by PayasR** [comment]
the point is, does this issue still make sense? do we actually require cpp/java implementations?

**Comment by jbenet** [comment]
@PayasR yes, some people may want to use an ipfs library in those languages. it's not a priority for the core team though.

**Comment by patcon** [comment]
https://github.com/ipfs/java-ipfs-api for anyone stumbling on this later

**Comment by SalvatoreT** [comment]
I'm interested in a Java/Kotlin IPFS implementation (not just API). Is there currently a project underway? @diasdavid seemed to [have a plan for how to get started](https://github.com/ipld/ipld/issues/24#issuecomment-326730076).

**Comment by Agorise** [comment]
C-IPFS is now functional, pre-release of v1.0 is online, API and IPNS is working, just doing all the testing and fixing and testing and fixing now... Getting it to play nice with the Go version.. priceless ;) 
https://github.com/Agorise?tab=repositories 
Peace, Love, and Agorism, 
  kenCode

**Comment by xuruijing** [comment]
@whyrusleeping Have you successfully ported go-ipfs to iOS? Can you share your project?

**Comment by maxbrito500** [comment]
Hello, any progress on having a Java implementation of the IPFS node?
