### ISSUE TITLE
what is the rationale for encouraging multiple implementations of ipfs?

### ISSUE THREAD

**Issue by danoctavian** [ipfs/ipfs#74]
Why not stick to writing a single implementation (eg. go-ipfs) and just have some interface for interacting with the ipfs daemon with implementations in many languages?

**Comment by bedeho** [comment]
I've also wondered about this.

**Comment by jbenet** [comment]
Go doesn't run on the browser

**Comment by lstagner** [comment]
You might be able to use [gopherjs](https://github.com/gopherjs/gopherjs) or llvm+emscripten. Even if its sub-optimal it would be interesting to see if it can be done.

**Comment by jbenet** [comment]
@lstagner indeed. would need to build connectors for webrtc and websockets as the comm, but it might just work :)

**Comment by io7m** [comment]
I think the main value is in having different people try to implement the specification in as many different ways as possible: You soon learn where the specification is weak! This is obviously not IPFS specific.

**Comment by 5paceManSpiff** [comment]
@io7m I think having multiple implementations will allow for better embedded application specific clients long term.  If the protocol becomes the standard, not the implementation, experimentation with implementation will be more encouraged.

**Comment by non** [comment]
Agreed -- and in fact, if there is only ever one implementation then it is likely that either there will be no complete specification, or that the specification will be obsolete/incomplete/incompatible with the implementation. In that case, folks who want to experiment will end up having to try to reverse engineer the actual protocol from the implementation.

**Comment by daviddias** [comment]
Lot has happened since the opening of this issue :) I'm closing here but if you want to continue the discussion, please do so at https://discuss.ipfs.io/
