### ISSUE TITLE
IPFS and HTTP headers.

### ISSUE THREAD

**Issue by tritonresearch** [ipfs/ipfs#75]
Does IPFS provide/plan to provide control over HTTP headers when hitting an IPFS endpoint?

**Comment by whyrusleeping** [comment]
Could you elaborate a bit on what you are looking for?

**Comment by jbenet** [comment]
@tritonresearch we can support for something like that easily in the go-ipfs HTTP gateway, for people that run their own. setting headers on the global gateways (those _we_ run) is a much trickier subject.

**Comment by opn** [comment]
Yes - I'd like to be able to set wildcard CORS headers for a local GO server - so that we can run Federated Wiki with IPFS serving some of the content (media assets).

**Comment by jbenet** [comment]
@opn we'll be setting arbitrary headers via the go-ipfs config soon (discussion in https://github.com/ipfs/go-ipfs/pull/1444). if you need this asap, we can try to get this in this week :)  

(also many of us will be down in portland this week, if you're there too https://github.com/ipfs/community/issues/38 )

**Comment by almereyda** [comment]
@jbenet Unfortunately @opn and me are not in the US.

For our deployment scenario it would also be great if the CORS domains could be set by an environment variable, esp. interesting for running [IPFS in Docker containers](https://lab.allmende.io/allmende/docker-ipfs) where FUSE is not really available and some frontend applications way want to use the HTTP gateway.

[`node-ipfs`](https://github.com/ipfs/node-ipfs) seems a bit dated to integrate with [`wiki-node`](https://github.com/fedwiki/wiki-node).

**Comment by jbenet** [comment]
@almereyda @opn have we addressed all your needs so far? the CORS stuff has been merged for a while: https://github.com/ipfs/go-ipfs/pull/1529

```
    	ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
    	ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST"]'
    	ipfs config --json API.HTTPHeaders.Access-Control-Allow-Credentials '["true"]'
```

 and you can set arbitrary headers as well:

```
    	ipfs config --json API.HTTPHeaders.X-Special-Header '["so special :)"]'
    	ipfs config --json Gateway.HTTPHeaders.X-Special-Header '["so special :)"]'
```

> node-ipfs seems a bit dated to integrate with wiki-node.

yes we recently picked up on this. @diasdavid is leading the charge. Right now the modules are spread out, but will get more unified in coming weeks.

**Comment by diasdavid** [comment]
@ghost a lot has been done since this last comment (Aug 2015 was exactly when the implementation got started), check out all the new stuff at https://github.com/ipfs/js-ipfs

**Comment by daviddias** [comment]
I'm closing this issue as it seems to be resolved (i.e. Setting CORS headers is an option (https://github.com/ipfs/ipfs/issues/75#issuecomment-131293095), and the JS Implementation has progressed significantly). Please open a new one in case you find new issues. Thanks!
