### ISSUE TITLE
Data replication

### ISSUE THREAD

**Issue by ottuzzi** [ipfs/ipfs#81]
Hi,

is it possible to have a datum replicated? Say I have a file I care very much and I would like to be sure it is replicated at least on two nodes: is it possible? I briefly looked at examples but I did not see this option.
If it is not implemented is it possible to implement it? Does it make any sense in the IPFS specs?

Thanks in advance
Bye
Piero

**Comment by jbenet** [comment]
@ottuzzi yep:

```
# this gives you a hash
ipfs add <file>

# to replicate:
ipfs pin add -r <hash> 
```
