### ISSUE TITLE
RPC API for IPFS mountable over any socket or duplex stream

### ISSUE THREAD

**Issue by ehmry** [ipfs/ipfs#85]
I would like to see the command API served over raw TCP or unix sockets, essentially whatever the Go net package supports. Requests would be encoded in JSON, written to the stream, and the same JSON encoded responses as used in the HTTP api would be read off the stream.

My reason for this is that I want to write fairly low level IPFS integration stuff and so far driving an HTTP client has become much more of a hassle than simply opening a socket.

I don't think this would be too much work to implement, and I volunteer to do it if I can get some guidence on where to start amending things in go-ipfs.

**Comment by jbenet** [comment]
This shouldn't be too much work. Have to layer the go-ipfs commands lib over another transport. It's designed so this is straightforward to do. will reply later with more details on how

**Comment by jbenet** [comment]
The how is to provide an implementation like https://github.com/ipfs/go-ipfs/tree/master/commands/http but on unix domain sockets.
