### ISSUE TITLE
Unable to install IPFS

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/ipfs#88]
I'm actually not sure where to ask this, so I'm asking here. I went to the [ipfs website](http://ipfs.io/) and downloaded the Mac OSX binary, and moved it to `/usr/local/bin/`. 

`$ ipfs` did not register as a valid command. What am I missing?

**Comment by RichardLitt** [comment]
Ok. So, I am silly, and clearly I should have moved `ipfs/ipfs` into `usr/local/bin`, not the top folder with the License, Readme, and `install.sh` script.

How can we make sure this doesn't happen again? Can we call the top folder `install-ipfs`?

Finally, the website does not offer help for users looking to ask questions. It directs them to IRC, which is cool, but maybe other alternatives - like opening a ticket here, or emailing someone - would be good? Thoughts?

**Comment by jbenet** [comment]
This should be filed in https://github.com/ipfs/website as it's about directions there. 

> How can we make sure this doesn't happen again? Can we call the top folder `install-ipfs`?

Sure. 

> Finally, the website does not offer help for users looking to ask questions. It directs them to IRC, which is cool, but maybe other alternatives - like opening a ticket here, or emailing someone - would be good? Thoughts?

we could add a repo like github.com/ipfs/support and people could file tickets there.
