### ISSUE TITLE
Dynamic content and file notification

### ISSUE THREAD

**Issue by unode** [ipfs/ipfs#94]
Hi everyone,

I've been reading about IPFS and some questions immediately popped up. These are mostly from the user perspective and very naive as in "How would [insert name] run on IPFS?".

Straight to questions:
- Would it be possible to implement something like [inotify](https://en.wikipedia.org/wiki/Inotify) to get notified when new files are created?
- It's clear that IPFS works best for static content. Do you have any ideas for dealing with the following use-cases: AJAX & friends (partial content update), web-services (computation on servers, software not available), "real-time" multi-user systems (forums, chats, etc...). Mostly things that fit the centralized model quite well, not so easily the distributed model.

Some points regarding the questions:
- Starting from the bottom. Multi-user systems will easily branch into multiple website versions. Would this ever be unified or one would have to jump between different website versions to track the different conversations? How would logins (privacy?) work in this case?
- For web-services, "centralized" servers would still be necessary to perform the computation. Consider the situation where the software running in the "backend" is **not** available (publicly).
- Still in the web-service case, how would "upload" work at all? Files would be dropped in a folder monitored by the "server" perhaps? Thinking of a website like www.virustotal.com where users upload files that will be scanned by several anti-virus software.
- Still on the anti-virus software example. After processing the user supplied files, how would the user know that the analysis report is available?

Thanks and apologies if some of these questions have been answered elsewhere.

**Comment by jbenet** [comment]
Would you mind asking these in https://github.com/ipfs/faq ? we can answer them there. (search first pls)

**Comment by daviddias** [comment]
Closing out of inactivity. The new best location for these questions is: https://discuss.ipfs.io
