### ISSUE TITLE
Apply chunking to large link list objects

### ISSUE THREAD

**Issue by ion1** [ipfs/ipfs#96]
Would it be useful to add a possible level of indirection and apply chunking to large link lists?

[The real world directory object for all the RFCs](https://ipfs.io/ipns/QmbuG3dYjX5KjfAMaFQEPrRmTRkJupNUGRn1DXCgKK5ogD/archives/RFCs
) is 421 kB in size for instance:

```
% ipfs object stat /ipns/QmbuG3dYjX5KjfAMaFQEPrRmTRkJupNUGRn1DXCgKK5ogD/archives/RFCs
NumLinks: 7715
BlockSize: 421110
```

One could imagine large directories with frequent small updates benefitting from being chunked themselves.

**Comment by jbenet** [comment]
yeah we need to shard directories. there is ongoing work to figure out exactly how to do this neatly.

**Comment by lgierth** [comment]
We've seen very large nodes with registry-mirror (napkin calculation ~14 MB), these need sharding very badly

**Comment by crazysoldier** [comment]
i also looking forward to this. Maybe we wanna have a little blockchain to keep track on files/folders? So every File/Foledr change would trigger a transaction with the new hash. Every Key/pair could represent a Folder and every Transaction is a File/Folder change.

**Comment by jbenet** [comment]
moved sharding discussion here: https://github.com/ipfs/notes/issues/76
